---
instance:
  cluster:
    networkPolicy: false
    domain: "cluster.local"
  storage:
    class: "longhorn-fast"
    size: "10Gi"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/gelato/homeops.git"
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
    pullSecret: github-deploy-key
