---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 20.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: replication
    fullnameOverride: "redis-sentinel"
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly no
      # Disable RDB persistence, AOF persistence already enabled.
      databases 80
      maxmemory 2800mb
      maxmemory-policy volatile-lru
      maxclients 20000
      maxmemory-samples 5
      timeout 60
      tcp-keepalive 300
      lazyfree-lazy-eviction yes
      lazyfree-lazy-expire yes
      replica-ignore-maxmemory no
      repl-diskless-sync yes
      save ""
    auth:
      enabled: false
      sentinel: false
    rbac:
      create: true
    replica:
      replicaCount: 2
      updateStrategy:
        type: RollingUpdate
      persistentVolume:
        enabled: false
      resources:
        requests:
          cpu: 10m
          memory: 2Gi
        limits:
          memory: 10Gi
      automountServiceAccountToken: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    component: redis
                topologyKey: kubernetes.io/hostname
            - weight: 90
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    component: redis
                topologyKey: "topology.kubernetes.io/zone"
    sentinel:
      enabled: true
      masterSet: redis-sentinel
      masterService:
        enabled: true
    networkPolicy:
      enabled: false
    metrics:
      enabled: false
      image:
        repository: bitnami/redis-exporter
        tag: 1.67.0-debian-12-r4
        redisTargetHost: redis-sentinel
      serviceMonitor:
        enabled: true
        interval: 20s