---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/guarded
  - ./pvc.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
