# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app harbor-init
#   namespace: flux-system
# spec:
#   targetNamespace: storage
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   path: ./kubernetes/apps/storage/harbor/init
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 25m
#   postBuild:
#     substitute:
#       APP: *app
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app harbor
#   namespace: flux-system
# spec:
#   targetNamespace: storage
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   path: ./kubernetes/apps/storage/harbor/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   dependsOn:
#     - name: harbor-init
#   postBuild:
#     substitute:
#       APP: *app
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app harbor-webhook
  namespace: flux-system
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/storage/harbor/webhook
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # dependsOn:
  #   - name: harbor
  postBuild:
    substitute:
      APP: *app
