# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:eoRdF9U/i27fYYay/DxhVpR+jiYV1qC8ny8sqET/RZWpypYZ,iv:J/BlemHp6jMktPSiy6dxPgJfVbG1v+Z+XBS8DoFwuJI=,tag:vS08T+z9cCFwGgGbnnxOlw==,type:str]
  credentials.json: ENC[AES256_GCM,data:GRKcI6JRwwtkwsbb9gM4rHx4e8LDCOoa1RfSPfrJvXUYocKgen+bCiGPYv2UPQBRYt02KaAQunPf55JBvzMSWN8YcJCVVE6hK1RXjQT2Xf4IYx5NkjRNS6Ce491vAs2S1SkdUqfjJ7MZvZbejMZQEvmxBo1f1opkLsgMfUIIXe6eWv61xUThQ5b36zsUDnharze7Lh0V82oaN3Hwn+fcOsx55BqtN0Dd5NKf0jXgsw==,iv:rEwUDP9HqgJYrrulBVSxdtgf/zwlD7jRWwPuWYIsRYM=,tag:EYCL2SDXCHpV6osUCPhqeA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeldKanpiYlEvNERQYkVS
        cW5HQXhIbjVxUjgzdG1oNVlnWlJJQ0lRNFN3ClBNOGpldUJlLytlMXA5Rlk5L0Iy
        a3d2NEdHMEdXQTBpSzFSbGNrRE52SHMKLS0tIDhCTFZBc0ltOURwSnVlQ0RuRStv
        djNNY3hGOXhTNUNjUWh4VU1iZnRpMkUK6GPwQI348/rTmtJHNNuICOZ5rTy6Rge3
        DzjdBo/7qEyn5wf716PacktspoNeUrIprtDpz4jUfXgVG3giGinEbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T23:42:20Z"
  mac: ENC[AES256_GCM,data:LZdD0ElYW2Y0bXR7lJ87/HG7X897VD4DXreD4okQ8jKnpiqZ3XAUUukCsbPfsSF+m66ysvO8fuGl6y+NxEK+Vv9Ot+eY7N963Onj+nA53cuYV3iMdy7dGOMe7Kr3XXcV9eY7KKygZaagLEQlqWxg7G4ky3LFgp87SZKwsqlrNbI=,iv:2Gnrrb0jWHeFOIEwBvzWeW96G0wQCWOfKJGeF0QWEn0=,tag:ke3pp5AfWmlt0ZmyqYFAMA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
