# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ydVV1TGXQy3vVZ1rnzMznDmJMfZklgS30zJrpSdIlBM=,iv:wgL2H5nYdhoyRAqMzUBgnz1fHPeRj0wi5GbGvBTnqEs=,tag:111JadzKMuusoOhJ2bZEeg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN1JZWk5VWVYra0UzYmhQ
        VmJHa3lROXM5Q1liTW00MGJUTUU3eFVqTUc0ClRMeVlXMUwxd3didnBvWENCNDVG
        U0pVWGFnbm1qTytwOVdBMWJTL1l6S0EKLS0tIHFmbjdqbGNuQjIyclBDMlVxK0di
        bHl4TGdsS25RZk5CMnhYV2lKcUxpWU0KrVIa1MwizMrdWVsK/Q8nQM/TVPx3HrX4
        PmI4IT4us92sBmo4EQVwt/LXFsYKsuUQ9FhjPx/3ybEVLkddZOC+jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T21:10:10Z"
  mac: ENC[AES256_GCM,data:D/77up/GoYEJuy5nPlQvEeenNCjSiPVEAegT5wALeHXctEcQy/hExf6OUI2LOw4DysYC4bCSJvCK6svQpE3VwEu70pe6Do1cuF0nJz437EDD/1mP1adzgZJzu6+yZgYelwZYz433i8ASaKZXzmPyw0gQeoZDjUbCHgHCMRcBTmc=,iv:TMBpOXPpDuxoAF3+mO5JlZwMdLMJUm1cqMTsXNjJ/n4=,tag:wbDX9LIiVAPNfctL/yxQZA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
