# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:i8RhFniIX8OZ0BShNy/WtX8ctu9PJQXqiNJyxwAZT2c=,iv:9O78aAUqmFtNnnJo6CNH3i5AzNY+W5RaB2HBZhgHAxM=,tag:DhkHiStgLOGDaN/C9sY5tw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb0ZncXUxU1hJK2YxM2xj
        Y0dtR0JlcHNNMHBhUWV4VzVSVnIzM1NOcmpzCjhMWjhPM0svWGtjTHViOFVrWklX
        a2tQQzNhN1pGS2lIcEdRMFlES1RPWjQKLS0tICs3MkNYd0pVYTFTTmtnZFpzNDY1
        ZEEwdTJNZSt0SVNLaE5uclpTVzVtRGcKovYGlCDViA7vPCccTMZcz6nxrYp87J3e
        H0RkT6523iXK8oNs+XdjMJEQJIdyKXU256Y9SdOkmsba2nkf5TLqpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:58:49Z"
  mac: ENC[AES256_GCM,data:yf3zy+HyC6K2tFSk5NHfaki7Y0HEmsSQg2WCqBvukqharlakAVokpkx6vU4eBhJV32FcaiiFuAF2APFdFXS5yjJe5gz8Vn+27Qxt8ZXd5Vy6GNfdIfr122iiIK00qkWGiliG5WKNRmOpJBMmD39ViqSc+pERsjtHWrSpDTIjVRc=,iv:f/e3IB6fSxiXLLELMce5PHz6AhdAvrhokwAmmUdYQx0=,tag:avX22LCND9kvuN1lNrYxBQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
