# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vjljFGMqgjemuV4DcwUgnlsyX1nFvVUOeUSoAZnUjPU=,iv:FwjM+s/WbVU5559zgPMJK2UWm848rzfchPQg++OLki0=,tag:CrRowrANXLrWU+yumk4D/Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV0IrSGo1ZS94VXlPNEU0
        VVhVZmhNaUljRDY0T1pFWkdRUUlzUklXTUNJCkl3WWQ5d1pad1hqeUJLWDJGNisr
        Rk16T1N4NmpGTnFOTEp4ckFWdko3eG8KLS0tICtkSkd4OFJ1MXJmM2V3UTcrUWFU
        NnB1Z2RaN1JwZUd2bkFRYWdlTG5mODgKiFxEytS/TtgHDyK3fuVmfms28q0Sago7
        8DeVFmBv6oGh9fE2mDfyniW8oU1HX4WBhPXV/3GVWjZ5JkZAzVwY+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:20:08Z"
  mac: ENC[AES256_GCM,data:3pCVE1b99Bzqs2cOtof97+JYJ1x6IZW0hVALd6U8LK7QJW+f7TB1Oo/CDzqHbIYx/XhUzr1+Q3rhv+2ZHd1Om5e34MGg1TwNnfFdyD26kiKH3UhgBx7L26N3yd2Tm9OOeeqcqjvgyUyd1ZECDcof4AT6Td6MaCRvEA1H29Fuko8=,iv:xN4FRgd7gFQT4Aby3NL4jfQ41V7F9vP9s8KW/bcdZEU=,tag:ai9QeM8jgAGYN2AsbQ1bxA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
