---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 45Gi
  storageClassName: longhorn-fast
  volumeName: pvc-961c5211-c224-4376-affe-2a3b8a46c253