apiVersion: v1
kind: Secret
metadata:
    name: kitchenowl
stringData:
    # App
    JWT_SECRET_KEY: ${KITCHENOWL_JWT_TOKEN}
    # Database
    DB_TYPE: postgres
    DB_HOST: &dbhost "{{ .POSTGRES_HOST }}"
    DB_PORT: "5432"
    DB_NAME: &dbname kichenowl
    DB_USER: &dbuser kichenowl
    DB_PASSWORD: &dbpass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
    # Database Init
    INIT_POSTGRES_HOST: *dbhost
    INIT_POSTGRES_DBNAME: *dbname
    INIT_POSTGRES_USER: *dbuser
    INIT_POSTGRES_PASS: *dbpass
    INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
    INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"