# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:WuuZzeCLwxPZKT/1VVdD+gJIIqs43vj5XIrcQNO2lzSf9cla8vxm4A==,iv:dR/1JjXFX7qJ8C0XM5eDemT5zhg5yAxlUghzSsK5cI8=,tag:HbetJ+1cyWMLtxhVuoxlgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3hDZ0xTTE9QRkFDNmF5
            MVRXYUk3WGtLV2JIdkxsZkJwUGdLeGNDQVZvCjltaDY1dnJITEJXWmpGTWh0UlJC
            R2N3K253TEkvSWlLb2VIZmRoSEZvNzgKLS0tIGNTcEdqVUN4K2QzajJmeHZwUUdZ
            bVZGeS9FZHRjY0ZBU0VVdFBrRXBrd0kKnVpQ5jT4WFAK7g/BITDWNilDaNQNIO5e
            bCyNMH3bhENfKaT6QMrS/lvV1iOYMulv/nXYJvr/H0bkf7tNFEn+og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-10T10:41:01Z"
    mac: ENC[AES256_GCM,data:D/mFsH6iaGDCebiYl7aM33/Cv+XSeGXRuSsRJXYnnm4/GqWP7goj7xsS45M3dDvxHQgxoaiCohSokD3gL8SbevkgJmJyefvZZqfwK3h3s0nLQsU3mRNWaBZ+wYpoLeSeW+X6ZNqVEl1Z6Mlap5GPepgSda1LlALRxGXnvR8SnFE=,iv:9Wt7yDXh+brqRuLzhz+jvLo31EfVrak3Xj4D0v4wAPU=,tag:K9QKsgZgvUHyh9GFxV/Rsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
