# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mh7idlLjdldv92pCITW0mvHtsgk5aECkR69QYw/Twhrg3ze+ATPzeA==,iv:Tgy65EX9HvLVESFALATcod+vbZFrM3y1rxSHaKGyfC8=,tag:0Rn8Cs63ZjRzIHqFawd7Bw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZE54MW5pcVAwVzFKdXdu
        ZHJXVGZKTklTRUcwRzZva3ZFSVFpMm9jRmcwCko0Tm1HdmJmWU5UT3pmV2M4dzFF
        SFJuUHlHYnQyMWd0dUR3TlBxZ1lJWGcKLS0tIFkrUEc5ZmdTcG5TYlR6b1A5b2lW
        YmlpeFNNZTM1RGpEcVl0bWh2VFVRenMKY2aafpp+sIsvJO2ljxt7O4fmVvQkKGuM
        /i5JGsEMO7fFjrsd6JxJt5pE+gzlBf3wctQstKk38i/cpTK54BYafA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:58:49Z"
  mac: ENC[AES256_GCM,data:aVBLas8D0JS9R3Jj6XJ8OmNKNRbZbW0uWz7X2gg6xt1k1yeAfuNeyEYcTPAAglEhlWINnsAH5mqQvv5Hz9q1OI0sMAj+1KKpyYqEK7eJHP/NKL6jqi8i5AUZRjKAoDa3FKuZAxIdBJ3kJ7qDds7W7o3rNsRAZiZAwMm7Clrj8GI=,iv:eseuBreI9MwB6shAjuWHQ4ODc6OB1UU6eAJKhviIzjk=,tag:40jYRJzbWHwQD870DAri6w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
