# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:isbfQNh4esRkvsEILpYsvUhKhNewQLo8n0XnyBsewf1sTxdP0IEqmg==,iv:x0l6bRI4c52nOHJgQsPcEHfmGDjkjdPZsvz2uaSa9to=,tag:qVs1qBsx/0hco766VQ09gA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cC9OWWlkeFBNdmlIaEVI
        MnpuY0JxdVpDaUVrblhhUjU2UTkxOTZQcGxZClJ3Y3dGN1p6VGd6YW1JWTd6QVdw
        MWlWWlIwZkNmRlZpd212dDZicGFHNEUKLS0tIEZlbEcyeG5XdUwxVFZZZTFQVzZM
        VjNBMmgrUnYyVExPWllaSlZkUUtUMmcKn+2yMyIGS5SploBlddJiHrrUUYsHlarG
        gY83tH8MSdmV6fyuefwPqCfGLs9rqvrQUcKLR4+gVeX5+nJJyax7Sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T21:10:10Z"
  mac: ENC[AES256_GCM,data:ZtF6WQJkjFWc6jTj9LZDDCtlvl50/epngPiQ76i7V2jS3i2M8d14Y/Ankakv2gM3gZfYAjwBmjFyqB5b8/z9zYe+CVUPn1nrX3EzG/cbOsoyfPOcZXjMWZrYTgJWdSov0IFJMzg4xlBanTVBzeuDG2YwVldlZBeHtidyeDzzfRw=,iv:G/cxwv4e/lws3bJMIAv9fg/jqOUVHMRXmWypkdTaUc8=,tag:H/ZtuGs3/MrvT4DXlhAXIA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
