# yaml-language-server: $schema=https://frigate.skynerv.com/api/config/schema.json
mqtt:
  enabled: True
  host: mosquitto.home.svc.cluster.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 30

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /data/frigate.db

tls:
  enabled: False

audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

logger:
  default: warning
  logs:
    frigate.event: debug

auth:
  enabled: false

objects:
  track:
    - person
    - dog
    - car
    - bus
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

record:
  enabled: True
  sync_recordings: True
  retain:
    days: 3
    mode: all
  preview:
    quality: very_high
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 3
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 3
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 10
    objects:
      person: 10
      car: 10
  quality: 90

semantic_search:
  enabled: True

genai:
  # Optional: Enable AI description generation (default: shown below)
  enabled: True
  # Required if enabled: Provider must be one of ollama, gemini, or openai
  provider: ollama
  # Required if provider is ollama. May also be used for an OpenAI API compatible backend with the openai provider.
  base_url: http://ollama.ai.svc:11434
  model: hf.co/VanHolder/llava-saiga-8b-Q8_0-GGUF:Q8_0
  # Required if gemini or openai
  api_key: "{FRIGATE_GENAI_API_KEY}"
  # Optional: The default prompt for generating descriptions. Can use replacement
  # variables like "label", "sub_label", "camera" to make more dynamic. (default: shown below)
  prompt: "Проанализируй {label} на этих изображениях с камеры видеонаблюдения {camera}. Сосредоточься на действиях, поведении и потенциальном намерении {label}, а не просто на описании его внешнего вида."
  object_prompts:
    person: "Внимательно изучи главного героя на этих изображениях. Что он делает и что его действия могут указывать на его намерения (например, подходит к двери, выходит из помещения, стоит на месте)? Не описывай окружающую обстановку или статичные детали."
    car: "Обрати внимание на основной автомобиль на этих изображениях. Обратите внимание на его движение, направление или цель (например, парковка, приближение, объезд). Если это автомобиль доставки, укажи компанию."

go2rtc:
  streams:
    gates_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/301
      - "ffmpeg:gates_hq#audio=copy#audio=aac#audio=opus"
    gates_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/302
      - "ffmpeg:gates_lq#audio=copy#audio=aac#audio=opus"
    door_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/601
      - "ffmpeg:door_hq#audio=copy#audio=aac#audio=opus"
    door_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/602
      - "ffmpeg:door_lq#audio=copy#audio=aac#audio=opus"
    dvor_gates_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/401
      - "ffmpeg:dvor_gates_hq#audio=copy#audio=aac#audio=opus"
    dvor_gates_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/402
      - "ffmpeg:dvor_gates_lq#audio=copy#audio=aac#audio=opus"
    dom2_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/201
      - "ffmpeg:dom2_hq#audio=copy#audio=aac#audio=opus"
    dom2_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/202
      - "ffmpeg:dom2_lq#audio=copy#audio=aac#audio=opus"
    middle_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/101
      - "ffmpeg:middle_hq#audio=copy#audio=aac#audio=opus"
    middle_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/102
      - "ffmpeg:middle_lq#audio=copy#audio=aac#audio=opus"
    street_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/501
      - "ffmpeg:street_hq#audio=copy#audio=aac#audio=opus"
    street_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/502
      - "ffmpeg:street_lq#audio=copy#audio=aac#audio=opus"
    garden_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/701
      - "ffmpeg:garden_hq#audio=copy#audio=aac#audio=opus"
    garden_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@nvr.local:554/Streaming/Channels/702
      - "ffmpeg:garden_lq#audio=copy#audio=aac#audio=opus"
  webrtc:
    candidates:
      - 192.168.108.55:8555
cameras:
  gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/gates_hq
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/gates_lq
        #   roles:
        #     - detect
    detect:
      width: 848
      height: 480
      fps: 5
      enabled: True
    live:
      stream_name: gates_hq
      quality: 1
    webui_url: ""
    motion:
      mask:
        - 1,0.811,0.947,0.76,0.812,0.55,0.84,0.39,0.808,0.304,0.838,0.097,0.876,0,1,0
        - 0.257,0.604,0.256,1,0.23,1,0,1,0.001,0,0.482,0,0.507,0.023,0.177,0.403,0.234,0.631
        - 0.669,0.619,0.747,0.691,0.8,0.528,0.808,0.544,0.835,0.393,0.804,0.311,0.825,0.163,0.804,0.141,0.764,0.204,0.667,0.437,0.746,0.43
      threshold: 35
      contour_area: 25
    zones:
      inside_gates:
        coordinates: 0.94,0.881,0.946,0.767,0.867,0.64,0.801,0.54,0.751,0.698
        inertia: 2
        loitering_time: 1
        objects:
          - person
          - dog
          - car
      entryway:
        coordinates: 0.571,0.171,0.461,0.085,0.181,0.405,0.236,0.624
        inertia: 5
        loitering_time: 5
        objects:
          - car
          - bus
      guests:
        coordinates: 0.739,0.437,0.622,0.446,0.499,0.701,0.552,0.871
        inertia: 5
        loitering_time: 4
        objects:
          - person
      sidewalk:
        coordinates: 0.258,0.994,0.479,0.999,0.548,0.866,0.493,0.699,0.62,0.44,0.649,0.437,0.697,0.356,0.705,0.334,0.772,0.124,0.793,0.113,0.826,0.153,0.837,0.095,0.87,0,0.722,0.002,0.607,0.141,0.577,0.174,0.261,0.599
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
          - car
    review:
      alerts:
        labels:
          - car
          - person
          - bus
        required_zones:
          - entryway
          - guests
          - inside_gates
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 500
      quality: 100
    birdseye:
      order: 0

  door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/door_hq
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/door_lq
        #   roles:
        #     - detect
    detect:
      width: 848
      height: 480
      fps: 5
      enabled: True
    live:
      stream_name: door_hq
      quality: 1
    webui_url: "https://192.168.108.104/"
    motion:
      mask:
        - 0.002,0.468,0.32,0.566,0.37,0.46,0.383,0.413,0.474,0.088,0.744,0.109,0.747,0.011,0.799,0.009,0.87,0.6,0.859,0.604,0.838,0.871,0.739,0.852,0.736,0.893,0.698,0.889,0.678,1,1,1,1,0,0,0
      threshold: 35
      contour_area: 25
    zones:
      near_the_door:
        coordinates: 0.096,1,0.67,1,0.689,0.895,0.171,0.855
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      dvor:
        coordinates: 0.735,0.482,0.375,0.459,0.317,0.584,0.177,0.843,0.732,0.875
        inertia: 5
        objects:
          - person
      tropinka:
        coordinates: 0.866,0.588,0.793,0,0.75,0,0.75,0.561
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      kuhnya:
        coordinates: 0.74,0.567,0.739,0.841,0.834,0.852,0.855,0.595
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      parkovka:
        coordinates: 0.734,0.471,0.733,0.121,0.476,0.102,0.378,0.447
        inertia: 5
        objects:
          - person
          - dog
      sad:
        coordinates: 0.311,0.573,0.275,0.562,0,0.48,0,0.566,0,1,0.081,1
        inertia: 5
        objects:
          - person
          - dog
    review:
      alerts:
        labels:
          - person
        required_zones:
          - near_the_door
          - dvor
          - tropinka
          - parkovka
          - sad
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 1

  dvor_gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dvor_gates_hq
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/dvor_gates_lq
        #   roles:
        #     - detect
    detect:
      width: 848
      height: 480
      fps: 5
      enabled: True
    live:
      stream_name: dvor_gates_hq
      quality: 1
    webui_url: "https://192.168.108.210/"
    motion:
      mask:
        - 0.643,0.507,0.729,1,1,1,0.998,0.521,1,0.163,0.876,0.061,0.778,0,0.594,0,0.594,0.077,0.637,0.134
        - 0.412,0.163,0.373,0.349,0.257,0.357,0.161,0.707,0.288,0.724,0.288,0.751,0.211,0.867,0.178,1,0,1,0,0,0.207,0,0.407,0
    zones:
      before_gates:
        coordinates: 0.395,0.277,0.362,0.416,0.617,0.404,0.603,0.264
        inertia: 3
        loitering_time: 1
        objects:
          - person
          - car
      before_gates_2:
        coordinates: 0.396,0.269,0.601,0.257,0.585,0.028,0.455,0.035,0.409,0.045,0.416,0.167
        inertia: 3
        loitering_time: 1
        objects:
          - person
          - car
      at_the_door:
        coordinates: 0.168,0.7,0.29,0.718,0.366,0.355,0.259,0.364
        inertia: 3
        loitering_time: 1
        objects:
          - person
      in_the_garden:
        coordinates: 0.638,0.454,0.634,0.137,0.596,0.085,0.626,0.424
        inertia: 5
        loitering_time: 2
        objects:
          - person
      driveway:
        coordinates: 0.298,0.746,0.213,0.871,0.184,0.997,0.688,0.997,0.66,0.747
        inertia: 5
        loitering_time: 2
        objects:
          - person
          - car
      driveway_2:
        coordinates: 0.237,1,0.698,1,0.613,0.412,0.356,0.425
        inertia: 5
        loitering_time: 2
        objects:
          - person
          - car
    review:
      alerts:
        labels:
          - car
          - person
        required_zones:
          - before_gates
          - before_gates_2
          - at_the_door
          - in_the_garden
          - driveway
          - driveway_2
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 2

  dom2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dom2_hq
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dom2_lq
          roles:
            - detect
    detect:
      width: 736
      height: 416
      fps: 5
      enabled: True
    live:
      stream_name: dom2_hq
      quality: 1
    webui_url: "https://192.168.108.215/"
    motion:
      mask:
        - 0.049,1,0.001,0.996,0.001,0.001,0.996,0.003,0.999,0.996,0.648,1,0.62,0.849,0.872,0.761,0.868,0.61,0.581,0.635,0.578,0.463,0.532,0.47,0.517,0.51,0.526,0.698,0.359,0.718,0.215,0.738,0.057,0.928
      threshold: 55
      contour_area: 40
    zones:
      kacheli:
        coordinates: 0.619,0.838,0.581,0.642,0.865,0.619,0.868,0.756
        inertia: 5
        loitering_time: 3
        objects:
          - person
      dom2_tropinka:
        coordinates: 0.528,0.607,0.567,0.609,0.643,1,0.55,1
        inertia: 5
        loitering_time: 2
        objects:
          - person
      lavka:
        coordinates: 0.218,0.744,0.528,0.704,0.542,1,0.053,1,0.064,0.931
        inertia: 5
        loitering_time: 2
        objects:
          - person
    review:
      alerts:
        labels:
          - person
        required_zones:
          - kacheli
          - dom2_tropinka
          - lavka
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 3

  street:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/street_hq
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/street_lq
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 5
      enabled: True
    live:
      stream_name: street_hq
      quality: 1
    motion:
      mask:
        - 0.319,1,0.484,0.664,0.431,0.481,0.352,0,0.001,0.001,0,0.413
        - 0.866,0.249,1,0.414,1,0,0.667,0,0.767,0.295
        - 0.359,0.007,0.437,0.47,0.492,0.666,0.678,0.646,0.687,0.39,0.736,0.381,0.734,0.21,0.665,0.013,0.646,0.009
    zones:
      u_okna:
        coordinates: 0,1,0,0.439,0.301,1,0.141,1
        inertia: 5
        objects:
          - person
      za_zaborom:
        coordinates: 0.691,0.399,0.736,0.391,0.829,1,0.676,1
        inertia: 5
        objects:
          - person
      pod_oknami:
        coordinates: 0.486,0.681,0.676,0.66,0.665,1,0.333,1
        inertia: 5
        objects:
          - person
    review:
      alerts:
        labels:
          - person
        required_zones:
          - u_okna
          - za_zaborom
          - pod_oknami
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 4

  middle:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/middle_hq
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/middle_lq
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 5
      enabled: True
    live:
      stream_name: middle_hq
      quality: 1
    motion:
      mask:
        - 0.188,0.988,0.108,0.813,0.05,0.6,0.046,0.553,0.002,0.556,0.001,0.004,0.334,0.003,0.335,0.994
        - 0.341,0.455,0.409,0.412,0.487,0.418,0.62,0.549,0.614,0.99,0.692,0.99,0.807,0.836,0.851,0.73,0.905,0.547,0.919,0.499,0.998,0.497,0.996,0.003,0.342,0.004
    zones:
      deepwalk:
        coordinates: 0.005,0.563,0.042,0.561,0.046,0.606,0.101,0.811,0.184,0.994,0.001,0.997
        inertia: 2
        objects:
          - person
          - dog
      near_doghouse:
        coordinates: 0.697,0.992,0.809,0.847,0.994,0.912,0.998,0.994
        inertia: 2
        objects:
          - person
      garden_entrance:
        coordinates: 0.343,0.988,0.341,0.47,0.412,0.427,0.488,0.428,0.617,0.56,0.606,0.992
        inertia: 2
        objects:
          - person
      doghouse:
        coordinates: 0.816,0.835,0.995,0.898,0.998,0.579,0.907,0.559
        inertia: 2
        objects:
          - person
          - dog
    review:
      alerts:
        labels:
          - person
          - dog
        required_zones:
          - deepwalk
          - near_doghouse
          - garden_entrance
          - doghouse
    webui_url: ""
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 500
      quality: 100
    birdseye:
      order: 6

  garden:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garden_hq
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/garden_lq
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    live:
      stream_name: garden_hq
      quality: 1
    motion:
      mask:
        - 0.42,0.5,0.441,0.781,0.503,0.857,0.568,0.849,0.639,0.915,0.741,0.84,0.726,0.709,0.672,0.606,0.663,0.477,0.682,0.41,0.625,0.406,0.605,0.263,0.489,0.323,0.509,0.476
        - 0.605,0.251,0.48,0.321,0.393,0.337,0.371,0.524,0.214,0.551,0.132,0.746,0.16,0.995,0.002,0.995,0.001,0.004,0.566,0
        - 0.61,0.25,0.571,0.003,0.995,0.006,0.995,0.989,0.898,0.989,0.95,0.526,0.787,0.192
    zones:
      garden_zone:
        coordinates: 0.163,0.99,0.892,0.992,0.946,0.525,0.894,0.409,0.782,0.196,0.609,0.26,0.631,0.401,0.691,0.402,0.668,0.479,0.676,0.598,0.734,0.698,0.75,0.841,0.639,0.923,0.57,0.859,0.502,0.869,0.438,0.785,0.416,0.496,0.503,0.468,0.487,0.333,0.394,0.347,0.376,0.533,0.212,0.559,0.136,0.752
        inertia: 2
        objects:
          - person
          - dog
    review:
      alerts:
        labels:
          - person
          - dog
        required_zones:
          - garden_zone
    webui_url: ""
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 500
      quality: 100
    birdseye:
      order: 7

ui:
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"

telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: False
    intel_gpu_stats: True
    network_bandwidth: True
  version_check: True

camera_groups:
  outside:
    cameras:
      - gates
      - dvor_gates
      - dom2
      - street
      - door
      - middle
    icon: LuCar
    order: 0