# yaml-language-server: $schema=https://frigate.skynerv.com/api/config/schema.json
mqtt:
  enabled: True
  host: mosquitto.home.svc.cluster.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 30

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /data/frigate.db

tls:
  enabled: False

audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

logger:
  default: warning
  logs:
    frigate.event: debug

auth:
  enabled: false

birdseye:
  enabled: False
  restream: True
  width: 2304
  height: 1296
  quality: 1
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

detect:
  width: 640
  height: 360
  fps: 10
  enabled: True

motion:
  threshold: 35
  contour_area: 20

objects:
  track:
    - person
    - dog
    - car
    - bus
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  retain:
    days: 14
    mode: all
  preview:
    quality: very_high
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: False
  crop: False
  required_zones: []
  retain:
    default: 30
    objects:
      person: 30
      car: 30
  quality: 90

go2rtc:
  streams:
    gates_hq:
      - rtsp://admin:12332145@192.168.108.104:554/stream1
      - "ffmpeg:gates_hq#audio=copy#audio=aac#audio=opus"
    gates_lq:
      - rtsp://admin:12332145@192.168.108.104:554/stream2
      - "ffmpeg:gates_lq#audio=copy#audio=aac#audio=opus"
    door_hq:
      - rtsp://admin:12332145@192.168.108.227:554/stream1
      - "ffmpeg:door_hq#audio=copy#audio=aac#audio=opus"
    door_lq:
      - rtsp://admin:12332145@192.168.108.227:554/stream2
      - "ffmpeg:door_lq#audio=copy#audio=aac#audio=opus"
    dvor_gates_hq:
      - rtsp://admin:12332145@192.168.108.210:554/stream1
      - "ffmpeg:dvor_gates_hq#audio=copy#audio=aac#audio=opus"
    dvor_gates_lq:
      - rtsp://admin:12332145@192.168.108.210:554/stream2
      - "ffmpeg:dvor_gates_lq#audio=copy#audio=aac#audio=opus"
    dom2_hq:
      - rtsp://admin:12332145@192.168.108.215:554/stream1
      - "ffmpeg:dom2_hq#audio=copy#audio=aac#audio=opus"
    dom2_lq:
      - rtsp://admin:12332145@192.168.108.215:554/stream2
      - "ffmpeg:dom2_lq#audio=copy#audio=aac#audio=opus"
    street_hq:
      - rtsp://admin:12332145@192.168.108.197:554/ch0_0
      - "ffmpeg:street_hq#video=h264#hardware#audio=aac#audio=opus"
    street_lq:
      - rtsp://admin:12332145@192.168.108.197:554/ch0_1
      - "ffmpeg:street_lq#video=h264#hardware#audio=aac#audio=opus"
  webrtc:
    candidates:
      - 192.168.108.55:8555
cameras:
  gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 10
      enabled: True
    live:
      stream_name: gates_hq
      quality: 1
    webui_url: ""
    motion:
      mask:
        - 1,0.811,0.947,0.76,0.812,0.55,0.84,0.39,0.808,0.304,0.838,0.097,0.876,0,1,0
        - 0.257,0.604,0.256,1,0.23,1,0,1,0.001,0,0.482,0,0.507,0.023,0.177,0.403,0.234,0.631
        - 0.669,0.619,0.72,0.664,0.781,0.509,0.808,0.544,0.835,0.393,0.804,0.311,0.825,0.163,0.804,0.141,0.764,0.204,0.667,0.437,0.746,0.43
      threshold: 35
      contour_area: 25
    zones:
      inside_gates:
        coordinates: 0.94,0.881,0.946,0.767,0.867,0.64,0.781,0.518,0.724,0.669
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
          - car
      entryway:
        coordinates: 0.571,0.171,0.461,0.085,0.181,0.405,0.236,0.624
        inertia: 5
        loitering_time: 5
        objects:
          - car
          - bus
      guests:
        coordinates: 0.739,0.437,0.622,0.446,0.499,0.701,0.552,0.871
        inertia: 5
        loitering_time: 6
        objects:
          - person
      sidewalk:
        coordinates: 0.258,0.994,0.479,0.999,0.548,0.866,0.493,0.699,0.62,0.44,0.649,0.437,0.697,0.356,0.705,0.334,0.772,0.124,0.793,0.113,0.826,0.153,0.837,0.095,0.87,0,0.722,0.002,0.607,0.141,0.577,0.174,0.261,0.599
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
          - car
    review:
      alerts:
        labels:
          - car
          - person
          - bus
        required_zones:
          - entryway
          - guests
          - inside_gates
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 500
      quality: 100
    birdseye:
      order: 0
  door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/door_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/door_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 10
      enabled: True
    live:
      stream_name: door_hq
      quality: 1
    webui_url: "https://192.168.108.104/"
    motion:
      mask:
        - 0.002,0.468,0.32,0.566,0.37,0.46,0.383,0.413,0.474,0.088,0.744,0.109,0.747,0.011,0.799,0.009,0.87,0.6,0.859,0.604,0.838,0.871,0.739,0.852,0.736,0.893,0.698,0.889,0.678,1,1,1,1,0,0,0
      threshold: 35
      contour_area: 25
    zones:
      near_the_door:
        coordinates: 0.096,1,0.67,1,0.689,0.895,0.171,0.855
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      dvor:
        coordinates: 0.735,0.482,0.375,0.459,0.317,0.584,0.177,0.843,0.732,0.875
        inertia: 5
        objects:
          - person
      tropinka:
        coordinates: 0.866,0.588,0.793,0,0.75,0,0.75,0.561
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      kuhnya:
        coordinates: 0.74,0.567,0.739,0.841,0.834,0.852,0.855,0.595
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      parkovka:
        coordinates: 0.734,0.471,0.733,0.121,0.476,0.102,0.378,0.447
        inertia: 5
        objects:
          - person
          - dog
      sad:
        coordinates: 0.311,0.573,0.275,0.562,0,0.48,0,0.566,0,1,0.081,1
        inertia: 5
        objects:
          - person
          - dog
    review:
      alerts:
        labels:
          - person
        required_zones:
          - near_the_door
          - dvor
          - tropinka
          - parkovka
          - sad
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 1
  dvor_gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dvor_gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dvor_gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 10
      enabled: True
    live:
      stream_name: dvor_gates_hq
      quality: 1
    webui_url: "https://192.168.108.210/"
    motion:
      mask:
        - 0.643,0.507,0.729,1,1,1,0.998,0.521,1,0.163,0.876,0.061,0.778,0,0.594,0,0.594,0.077,0.637,0.134
        - 0.412,0.163,0.373,0.349,0.257,0.357,0.161,0.707,0.288,0.724,0.288,0.751,0.211,0.867,0.178,1,0,1,0,0,0.207,0,0.407,0
    zones:
      before_gates:
        coordinates: 0.395,0.277,0.362,0.416,0.617,0.404,0.603,0.264
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - car
      before_gates_2:
        coordinates: 0.396,0.269,0.601,0.257,0.585,0.028,0.455,0.035,0.409,0.045,0.416,0.167
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - car
      at_the_door:
        coordinates: 0.168,0.7,0.29,0.718,0.366,0.355,0.259,0.364
        inertia: 5
        loitering_time: 3
        objects:
          - person
      in_the_garden:
        coordinates: 0.638,0.454,0.634,0.137,0.596,0.085,0.626,0.424
        inertia: 5
        loitering_time: 2
        objects:
          - person
      driveway:
        coordinates: 0.298,0.746,0.213,0.871,0.184,0.997,0.688,0.997,0.66,0.747
        inertia: 5
        loitering_time: 2
        objects:
          - person
          - car
      driveway_2:
        coordinates: 0.237,1,0.698,1,0.613,0.412,0.356,0.425
        inertia: 5
        loitering_time: 2
        objects:
          - person
          - car
    review:
      alerts:
        labels:
          - car
          - person
        required_zones:
          - before_gates
          - before_gates_2
          - at_the_door
          - in_the_garden
          - driveway
          - driveway_2
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 2
  dom2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dom2_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dom2_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 736
      height: 416
      fps: 10
      enabled: True
    live:
      stream_name: dom2_hq
      quality: 1
    webui_url: "https://192.168.108.215/"
    motion:
      mask:
        - 0.049,1,0.001,0.996,0.001,0.001,0.996,0.003,0.999,0.996,0.648,1,0.62,0.849,0.872,0.761,0.868,0.61,0.581,0.635,0.578,0.463,0.532,0.47,0.517,0.51,0.526,0.698,0.359,0.718,0.215,0.738,0.057,0.928
      threshold: 55
      contour_area: 40
    zones:
      kacheli:
        coordinates: 0.619,0.838,0.581,0.642,0.865,0.619,0.868,0.756
        inertia: 5
        loitering_time: 3
        objects:
          - person
      dom2_tropinka:
        coordinates: 0.528,0.607,0.567,0.609,0.643,1,0.55,1
        inertia: 5
        loitering_time: 2
        objects:
          - person
      lavka:
        coordinates: 0.218,0.744,0.528,0.704,0.542,1,0.053,1,0.064,0.931
        inertia: 5
        loitering_time: 2
        objects:
          - person
    review:
      alerts:
        labels:
          - person
        required_zones:
          - kacheli
          - dom2_tropinka
          - lavka
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 3
  street:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/street_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/street_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: street_hq
      quality: 1
    motion:
      mask:
        - 0.205,0.796,0.312,0.417,0.476,0.41,0.474,0.294,0.536,0.291,0.538,0.188,0.626,0.072,0.649,0,0.001,0.001,0,0.413
        - 0.825,0.288,1,0.495,1,0,0.66,0,0.632,0.085
    zones:
      u_okna:
        coordinates: 0,1,0,0.425,0.199,0.796,0.141,1
        inertia: 5
        objects:
          - person
      za_zaborom:
        coordinates: 0.479,0.306,0.527,0.301,0.638,1,0.492,1
        inertia: 5
        objects:
          - person
      pod_oknami:
        coordinates: 0.314,0.425,0.464,0.414,0.441,1,0.152,1
        inertia: 5
        objects:
          - person
    review:
      alerts:
        labels:
          - person
        required_zones:
          - u_okna
          - za_zaborom
          - pod_oknami
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 4

ui:
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"

telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: False
    intel_gpu_stats: True
    network_bandwidth: False
  version_check: True

camera_groups:
  outside:
    cameras:
      - gates
      - dvor_gates
      - dom2
      - street
      - door
    icon: LuCar
    order: 0