---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-machine-learning
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: immich-server
      namespace: media
    - name: immich-microservices
      namespace: media
  values:
    controllers:
      immich-machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.143.1@sha256:cc94659771d7e394d6406ebb0664069f2523062fda4f934def31648e903c4de2
            env:
              TZ: ${TIMEZONE}
              MPLCONFIGDIR: "/cache/matplotlib"
              MACHINE_LEARNING_PRELOAD__CLIP: "ViT-L-16-SigLIP-256__webli"
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
            envFrom:
              - configMapRef:
                  name: immich-configmap
              - secretRef:
                  name: immich
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 3003
                  initialDelaySeconds: 180
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 15m
                memory: 273M
              limits:
                memory: 16G
    service:
      app:
        controller: immich-machine-learning
        ports:
          http:
            port: 3003
    persistence:
      library:
        enabled: true
        existingClaim: immich-upload
        globalMounts:
          - path: *mediaLocation
      machine-learning-cache:
        existingClaim: immich-machine-learning-cache
        advancedMounts:
          immich-machine-learning:
            main:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache
              - path: /.config
                subPath: dotConfig
      geocoding-dump:
        existingClaim: immich-machine-learning-cache
        advancedMounts:
          immich-machine-learning:
            main:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
