---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: conduwuit
spec:
  interval: 30m
  chart:
    spec:
      chart: conduwuit
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: cronce
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: girlbossceo/conduwuit
      tag: "v0.4.3-d875e0c1c00d8e42b83dd562c3945c077898746d"
      pullPolicy: IfNotPresent

    config:
      server_name: "myautrix.skynerv.com"
      max_request_size: "20000000"
      allow_registration: true
      allow_federation: true

    extraEnv:
      # - CONDUWUIT_REGISTRATION_TOKEN: '12332145'
      - name: CONDUWUIT_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE
        value: 'true'
      - name: CONDUWUIT_ALLOW_CHECK_FOR_UPDATES
        value: 'true'

    service:
      type: ClusterIP

    ingress:
      enabled: true
      class: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      path: /
      hosts:
        - myautrix.${SECRET_DOMAIN}
      tls: true

    ## Persist configuration to a persistent volume
    persistence:
      data:
        enabled: true
        storageClass: longhorn-ssd
        accessMode: ReadWriteMany
        size: 16Gi

    resources:
      requests:
        cpu: "1"
        memory: "256Mi"
      limits:
        cpu: "2"
        memory: "512Mi"

