apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: security
stringData:
  SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:vkNq3A2YnWIzyyBen4V5GgEC8swaP60tfeDXdL4i,iv:/gYH6P23o3S7Pu8EMHUhQ5+DYPX9UfBBckjxzJKBejQ=,tag:lwjoGI8jldJG53KPsyeuDQ==,type:str]
  SECRET_AUTHENTIK_POSTGRES_DBNAME: ENC[AES256_GCM,data:Ebtz2DWe0aon,iv:lCd/Tz5SXZoz0XksMqylftJ3k5mENiI/kNygrLE3mGY=,tag:O6leFmj7pzBuGUMIfCaYPw==,type:str]
  SECRET_AUTHENTIK_POSTGRES_USERNAME: ENC[AES256_GCM,data:fHudk7QcnIGvgWZRHy4sWfwnaxV188CFaFQdxBBbEUCJMLlvtg==,iv:8gVf2CnUyoLGp273kkdPJtZgvjJLYf3dEngRB4fO850=,tag:q4AzpxdPlN9yorxfnblzCQ==,type:str]
  SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:sr8xbMmO0qbwyn8O1kjy9dQXKT6iEZphv2OXr0oLIoeX0/MKnA==,iv:+acvWhfDFS6Re4uQdBcws/nJQAfxPkPijeSu0+4Ok3g=,tag:RXTOWvCCPTukIBTcOcaqOA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:OG7NsnEj3dNq,iv:uH1DfTU7U3anHwJUhZFgYQ4g+4JPeYE3cwIX818fK8U=,tag:PE+8rUnkFJeQE6iK4Wi0Qg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pIShRSQIlRu3moiNo5/pSHHfhIyIdAx3RWAumq1U/XoCbq1CF9X+8Q==,iv:HZ0VkomTfmO3CYeIWBK87x9GlKLTJeRvuoND3mkeekU=,tag:G+b1D7UY4906uPLc8spwMw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:WGtNM2pApbE/fED/SWWSKfTwYLravdtmwJ5OsmOmocs5s6D5lw==,iv:V2hfgqnXrElPz7Q165MIQHtWnBdRByL9WW/2EZoDoqU=,tag:ESTPsGmgOMhU82/PUqAgJg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:N3UDWS2K7AExg1//NWilzu3TgGFeDhi0Rjn8W5qu50OCVj7vhQ==,iv:KrFerrhuFNDaSeNjj0PBZZpCPxf0PycWZSxeoy0Wd9g=,tag:IUNLPkoVp7CsB0NEs/e7TQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2OznF6Sn12qCGsOheivMhiYYiW2j4A==,iv:LbPQQ2coxQAfQ68N90KGAMZk+eC1S6oQxm6qL54F+nQ=,tag:pJzPSATuE0hhX4h/V3ma3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVFBIa1JnWXhsMmRHWDhE
        TlJadGN2dko4VkViNFlreHNzUjFMN0FvUXprCk40SHlFTW8zMVpFUCtDQ1RpNm8v
        dTBtOVI4NU8xRmlwY1o5bXVtajUyMzQKLS0tIDcxOUFiRWRsNVRoZnJyMnErRTZT
        TDRIelZSek8xYTE4TndBZVA0czN6VmMKFYhs/lkfQJzJ7Z9kftU37jBBCdNawoc5
        3ZMXF8wdtSOH+p5E2WrtE/h7qNi6Cw55tfnZsv0VC9NthIvYG8htMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T20:57:33Z"
  mac: ENC[AES256_GCM,data:FRIFr5wa3BTTEcZ3nY0UEr1f9hFQcl0rIPgqPBa3wwfMIAqSpBXZFvLZnOn4NqdRSs+f2CqKZfuFS0Wl8XO+Q8PKrGfV5e4AJIvv8V0KlqP/rc1H9hFZBavQKMcvhHxXcw90mXj0WAMDw+AQXMtWle/bUzJqWCSiKzj6LCjgToI=,iv:J7BONNBXo95naHy3igocRJMq2C570CUEA+uQkPpJg/8=,tag:VRrECU//3BqLEQqjlF8MmQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
