---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.8.1@sha256:55636d8a29588eea62d81d51acdafe38e0f694fb91801ab12dc1ed8c47b6439d
            env:
              TZ: ${TIMEZONE}
              SMTP_RELAY_SMTP_PORT: &port 25
              SMTP_RELAY_METRICS_PORT: &metricsPort 8080
              SMTP_RELAY_SERVER_PORT: 2525
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
          # topologySpreadConstraints:
          #   - maxSkew: 1
          #     topologyKey: kubernetes.io/hostname
          #     whenUnsatisfiable: DoNotSchedule
          #     labelSelector:
          #       matchLabels:
          #         app.kubernetes.io/name: *app
    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.108.80
        ports:
          http:
            port: *metricsPort
          smtp:
            port: *port
    persistence:
      config:
        enabled: true
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
