---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wyoming-whisper
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
    controllers:
      wyoming-whisper:
        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: latest
            args:
              - --model
              - large-v3
              - --language
              - ru
              # - --device
              # - cuda
            env:
              TZ: ${TIMEZONE}
            resources:
              limits:
                memory: 16Gi
                nvidia.com/gpu: 1
              requests:
                cpu: 100m
                memory: 1Gi
    service:
      app:
        controller: *app
        ports:
          whisper:
            enabled: true
            primary: true
            port: 10300
            protocol: TCP
    persistence:
      data:
        enabled: true
        existingClaim: *app