---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-fast