---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: swarmui
  namespace: ai
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  driftDetection:
    mode: enabled

  values:
    controllers:
      swarmui:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [1010]
          runtimeClassName: nvidia
        containers:
          app:
            image:
              repository: docker.io/eedev/swarmui-docker
              tag: latest@sha256:3b722bc65d9bd46a067933132d9ade8cf557480fcf9a3b4a747ceaa1909566d9
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 500m
                memory: 4Gi
              limits:
                memory: 6Gi
                nvidia.com/gpu: 1
    service:
      app:
        controller: swarmui
        ports:
          http:
            port: 7801
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "SwarmUI AI"
          hajimari.io/enable: "true"
          hajimari.io/instance: "admin"
          hajimari.io/group: "AI"
        hosts:
          - host: swarmui.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - swarmui.${SECRET_DOMAIN}
    persistence:
      data:
        enabled: true
        existingClaim: swarmui
        globalMounts:
          - path: /SwarmUI/Data
            subPath: data
          - path: /SwarmUI/dlbackend
            subPath: dlbackend
          - path: /SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
            subPath: dlnodes
          - path: /SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
            subPath: workflows
      output:
        type: nfs
        server: tower.local
        path: /mnt/user/ai-output
        globalMounts:
          - path: /SwarmUI/Output
            readOnly: false
      models:
        type: nfs
        server: tower.local
        path: /mnt/user/ai-models
        globalMounts:
          - path: /SwarmUI/Models