---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: swarmui
  namespace: ai
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  driftDetection:
    mode: enabled

  values:
    controllers:
      swarmui:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [1000]
          runtimeClassName: nvidia
        containers:
          app:
            image:
              repository: docker.io/mizeraj/swarmui-pt
              tag: 0.9.6@sha256:3636d4104ca47863da251787aeddc3269036d78765687a5703ff2d18c5f0ae10
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 500m
                memory: 4Gi
              limits:
                memory: 6Gi
                nvidia.com/gpu: 1
    service:
      app:
        controller: swarmui
        ports:
          http:
            port: 2254
          sync:
            port: 8384
          jupyter:
            port: 7888
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "SwarmUI AI"
          hajimari.io/enable: "true"
          hajimari.io/instance: "admin"
          hajimari.io/group: "AI"
        hosts:
          - host: swarm.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: swarm-sync.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: sync
          - host: swarm-jupyter.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: jupyter
        tls:
          - hosts:
              - swarm.${SECRET_DOMAIN}
              - swarm-sync.${SECRET_DOMAIN}
              - swarm-jupyter.${SECRET_DOMAIN}
    persistence:
      data:
        enabled: true
        existingClaim: swarmui
        globalMounts:
          - path: /workspace/SwarmUI/Data
            subPath: data
          - path: /workspace/SwarmUI/dlbackend
            subPath: dlbackend
          - path: /workspace/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
            subPath: dlnodes
          - path: /workspace/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
            subPath: workflows
          - path: /usr/local/lib/python3.11/dist-packages
            subPath: dist-packages
      output:
        type: nfs
        server: tower.local
        path: /mnt/user/ai-output
        globalMounts:
          - path: /workspace/SwarmUI/Output
      models:
        enabled: true
        existingClaim: swarmui-models
        globalMounts:
          - path: /workspace/SwarmUI/Models