---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swarmui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swarmui-models
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 400Gi
  storageClassName: longhorn-fast