---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swarmui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swarmui-dlbackend
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-fast