---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ha-fusion
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      hostNetwork: true
    controllers:
      ha-fusion:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/matt8707/ha-fusion
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              HASS_URL: https://hass.skynerv.com
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 23m
                memory: 105M
              limits:
                memory: 105M
    service:
      app:
        controller: *app
        type: ClusterIP
        ports:
          http:
            enabled: true
            primary: true
            protocol: TCP
            port: 5050
    persistence:
      config:
        enabled: true
        existingClaim: ha-fusion
        advancedMounts:
          ha-fusion:
            app:
              - path: "/app/data"
    ingress:
      app:
        className: internal
        hosts:
          - host: &host homedash.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host