---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-fusion
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-fast
  volumeName: pvc-909e5d63-603c-4430-8536-3350ffd6f2c1