---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: operator
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: minio-operator-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
    replace: true
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    operator:
      env:
        - name: PROMETHEUS_NAMESPACE
          value: "observability"
        - name: MINIO_PROMETHEUS_URL
          value: "http://vmselect-victoria-metrics.observability.svc.cluster.local:8481/select/0/prometheus"
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
      imagePullSecrets: [ ]
      runtimeClassName: ~
      initContainers: [ ]
      replicaCount: 1
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes: [ ]
      volumeMounts: [ ]
      nodeSelector: { }
      priorityClassName: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minio-operator
              topologyKey: kubernetes.io/hostname
      tolerations: [ ]
      topologySpreadConstraints: [ ]
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
          ephemeral-storage: 500Mi

    console:
      enabled: true
      env: [ ]
      imagePullSecrets: [ ]
      runtimeClassName: ~
      initContainers: [ ]
      replicaCount: 1
      nodeSelector: { }
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minio-operator
              topologyKey: kubernetes.io/hostname
      tolerations: [ ]
      topologySpreadConstraints: [ ]
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containerSecurityContext:
        runAsUser: 1000
        runAsNonRoot: true
      ingress:
        enabled: true
        ingressClassName: "internal"
        labels: { }
        annotations: { }
        tls:
          - hosts:
            - &host minio-operator.skynerv.com
            secretName: minio-operator-tls
        host: *host
        path: /
        pathType: Prefix
      volumes:
        - name: tmp
          emptyDir: {}
      volumeMounts:
        - name: tmp
          readOnly: false
          mountPath: /tmp/certs/CAs

      # extraResources:
      # - |
      #   apiVersion: networking.k8s.io/v1
      #   kind: Ingress
      #   metadata:
      #     annotations:
      #       kubernetes.io/tls-acme: "true"
      #     name: myminio-wildcard
      #     namespace: minio
      #   spec:
      #     ingressClassName: nginx
      #     rules:
      #     - host: "*.myminio.mydomain.com"
      #       http:
      #         paths:
      #         - backend:
      #             service:
      #               name: minio
      #               port:
      #                 name: http-minio
      #           path: /
      #           pathType: Prefix
      #     tls:
      #     - hosts:
      #       - "*.myminio.mydomain.com"
      #       secretName: myminio-wildcard-tls






