{
 "title": "Frigate",
 "tags": [
  "frigate",
  "coral"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Coral Inference Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_unit_ms{entity=\"sensor.coral_inference_speed\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "speed (ms)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"frigate\"} |= ``"
    }
   ]
  },
  {
   "title": "detection FPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.detection_fps\"}"
    }
   ]
  },
  {
   "title": "office",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.office_camera_fps\"}"
    },
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.office_detection_fps\"}"
    }
   ]
  },
  {
   "title": "driveway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.driveway_camera_fps\"}"
    },
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.driveway_detection_fps\"}"
    }
   ]
  },
  {
   "title": "front",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.lounge_camera_fps\"}"
    },
    {
     "expr": "hass_sensor_unit_fps{entity=\"sensor.lounge_detection_fps\"}"
    }
   ]
  },
  {
   "title": "FPS (all)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    { "expr": "hass_sensor_unit_fps", "legendFormat": "{{friendly_name}}" }
   ]
  }
 ]
}