---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: kms-media-plane
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: kms
          namespace: default