---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.8
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret

        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.1.2@sha256:d872fb529097df2d77b3c6f5e469b047f99d0d1c9f793a84ae27aa106e1f5d7e
            env:
              TZ: "${TIMEZONE}"
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              DB_ENGINE: postgres
              # SMTP_HOST: smtp.mailgun.org
              # SMTP_PORT: 587
              # SMTP_FROM_NAME: Mealie
              # SMTP_FROM_EMAIL: noreply@${SECRET_DOMAIN}
              # SMTP_AUTH_STRATEGY: TLS
              # SMTP_USER: mealie@${SECRET_DOMAIN}
              OPENAI_BASE_URL: http://ollama.ai.svc:11434/v1
              OPENAI_MODEL: gemma3n:latest
              OPENAI_WORKERS: 2
              OPENAI_SEND_DATABASE_DATA: true
              OPENAI_REQUEST_TIMEOUT: 10
            envFrom: *envFrom
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi

    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000

    ingress:
      app:
        enabled: true
        className: "internal"
        hosts:
          - host: "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: mealie-pvc
        globalMounts:
          - path: /app/data