apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
stringData:
    #ENC[AES256_GCM,data:d5F1tjYuMLp9,iv:PTjio1H5p5IudILBGf4dOKIWA3RmpipG8LNqXjhk6FQ=,tag:s5fqYRpeV25qyHejoK8lOw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:2dY3waT3I94=,iv:o5MfOCAEiaDKAiKQqxY9BJIqCyDe8TeaL2Ly8nJ8phU=,tag:D1X5y9MIS8S2yklD/n7ygw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:BBVW/k1iV3thJ6FiZZKcouRPyG1Pi3tO,iv:bufRbrpXkM8LPzYKgWUjaDNIn3yDGLeMIR388Bm8u28=,tag:r3CQSA6/IGjy8bOU57zzJg==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:sP8b1w==,iv:8KkigxOzvBPjk3t1MN501lZG7WHw5cXsQL803qLJbiY=,tag:yIm4oR4f8puSHkrf3JH69w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:5JgYekkmNsIzjg==,iv:d8Z+omIVxKCm0ErK2bGHle1L3iZeH8JC/oaHWYW1La8=,tag:iifzGOEzCBJxBTb1RuS+Mg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:GiCaXQAYBYTbwlVU/5LulFTq0POja7U+lUrz1tkMkSs=,iv:UAmZWHg/osNCALmcXcX4inq/gZMygNepixoWLysPfAo=,tag:2kL2nuMIeXfzS9/2h8Fz7w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:mrJlkZNQE8O7Gg==,iv:i3amGibzhC8qaMQEfE3RlMRPDD4kLq9Xu/t6XhTmN0A=,tag:EPqjqEo1y3NXbY6hoVD+qw==,type:str]
    #ENC[AES256_GCM,data:REOsFhvTgqAE4/GcsJo=,iv:5DO2Ay9ub05TDJrUTkLn4x1r1SIoKuHrRteEULEptA8=,tag:53O8HhcLlM1ZpJxLNdEBSA==,type:comment]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2XZcCc+uWXYcz5JdP8jnAswZCN6dokfq,iv:vb2liwJMlhio3+5eICLxMHgul5wNaw9GMdt5C7kCSaE=,tag:jE2j3C8l4D638aUL6pKwSA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cKUcMq2cFw8=,iv:KPkHn8gCVd8gTW4M0Zl5HU23NHDC+qDnQK+NFRbJvTs=,tag:ho9JVd+Z/q1vAjY6dyabQQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:2xgpDGYWImgxJQ==,iv:nzELOt0/DvzV92eyTCaThI1oqj4DXttwBTsIwbR3KAI=,tag:0eOXhrWUI7dsSLJtAnhblg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vF1U+YS4V1wMg4pwQTPH5vG6DHzY+0I72SdjaUiLWPs=,iv:ngsuLhdmSf+RjoZGfREHroYP7wO5osqBq+XkOom74pQ=,tag:E9YN8mGcEU64Dhi3Chevww==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:DoPwrzWH1AYTw1ZOKnMFWy2w3tLQTw==,iv:lV+euA2S48qR+mKeqdzRCdxRv0u4CvdIvuR3cH5qXPo=,tag:GbcdMg/awx89vxaF3bLpQA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kq/67csvyQypHY0j1ctSVMZ0+fMNGg==,iv:b61/0PYdErmVNQHQb74i9ns5Aud6sgL3PVWgLUiduXA=,tag:4nHCicwoxJsJjxnW2idhJA==,type:str]
sops:
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bTFrbURDdnl5cWE1Uk9B
            N1JPK280ZmZwSnFxVHR4dFRBTlN0US9jUkVVClVVQjdUWm5jempDUWlQamhVNHov
            RDhCblY1ODhYTDBONDNVdUhMTmp6OHcKLS0tIEFYNm5WUjlUZUc2MWVjNkNZem1U
            WEk5QVVSU3M2Y3dNcTVtZ2Y4VE5naHMKRpmXvNwAusA1X+zplFT75IeQAmeu6nAU
            kDHSnsxDezjygk3mEsmS9k55KDA1PNo+k73IzGWhtSw6Ic/DIn0NJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T21:30:58Z"
    mac: ENC[AES256_GCM,data:i+7JFiqBVxw00k+gmUrLgO8y7bFHtWygin2UM+Baa5xpWI6IJh8uy2lh0iPFblrSymrSWnuLrKsotvsJx3DxdN12z6Nbw5S7ZGmKxiHqEXn1FB5zCZ1dAcc1eHWE7OBm4eF+xs8m5WVBDucR/cy/k4khac7pOhYQMd/KU5o/Jgk=,iv:PhZjQ/JrgmpcyoiIMAQFlxkZ+7lPXmEn6Jn23vdBuys=,tag:3OBY6SuIFWhkD8y5+RJpkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
