---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    timeout: 15m
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - jellyfin
                topologyKey: "kubernetes.io/hostname"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0@sha256:fe26058628e9eb57b542204b76443b7304ed8820151d51b5c285e1828ca175a0
            env:
              TZ: ${TIMEZONE}
              QBT_WEBUI_PORT: &port 8049
              QBT_TORRENTING_PORT: &bittorrentPort 50413
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 93m
                memory: 5G
              limits:
                memory: 77G
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000, 568]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.108.20
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *bittorrentPort
            protocol: TCP
    ingress:
      app:
        className: internal
        hosts:
          - host: qb.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: qbittorrent
      buffer:
        existingClaim: buffer
        globalMounts:
          - path: /buffer