---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: ghost-database-user
  namespace: database
spec:
  user: ghost-user
  clusterRef:
    name: main
    namespace: database
  password:
    name: ghost-password
    key: PASSWORD
  allowedHosts:
    - "%"
  permissions:
    - schema: ghost-db
      tables: ["*"]
      permissions:
        - ALL