---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - recyclarr.yml=./configs/recyclarr.yml
      - settings.yml=./configs/settings.yml
generatorOptions:
  disableNameSuffixHash: true