---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - ./configs/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true