apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:Qb8l4vWU+T5aVr0CM8SX+sY=,iv:3qX6pz/EkJHOw0SlaNEcj/rDScGlh6zRPOrq+heDZOY=,tag:dgC1ThtYqaRmTamYjJ+sdA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:LPksa/TUtJL5BIDqHT6tid8=,iv:tqQWbJoqMd4xdCdEyA5hG+cnMeNl91Du3bpTvanZU4I=,tag:aWBwmZcujM1OFeujglS7sg==,type:str]
    PUSHOVER_API_TOKEN: ENC[AES256_GCM,data:okXcVTJLzyhQ4mkTfJJaQADztxEfQg==,iv:T/rOjjMY7Wh/Q8A1vFkLzA2rk10kD51kYdVrgyMhUKw=,tag:fiVZqaU/oz2EmuN6NhzAgQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:yN10Yt78Bc+FzxKTbQfo8NtMliM=,iv:+DXvHwpyuTdOjMVa+eDoHwq4uBMBnqUqtLgP+6e8tik=,tag:rqWmPAEL+hh3m4KUGooL4A==,type:str]
    PUSHOVER_URL: ENC[AES256_GCM,data:sRLMws929xfoUv2zSNB31o/0KFO5GANtqIlUuxJF0gwRIC5Epdf1CHpTTvC+BW+XsPJyKR3StBNXIm8=,iv:giWiUuR6hv6jUuIq7at2RjsKP4k27HLfT2wNrbmGhTs=,tag:vLTlBMwEAN4X7UXsxqzP1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMk1ROTU1cHZSVmNtRitZ
            NHBHTFJvRG9MR1ZxclZBQlZ2YUoxQUxHVld3CkVPK3dMN2pMS2JpNG5JcTMrZVVE
            dWJXTGR4WnY1VE96ODc4bWlQUFZ1Ym8KLS0tIEZUOHQySTMxVUpHL2piS2hUdENK
            dkEweW9kRFZaNE5qejlRb0FuSytFdlUKVH5lq4leHZO8GNSUtyvfuqqoxxkWIAPc
            CYyZUbQajjsWaPPmpZyDUb6uaJ5qSZzei/g04trUXFqAqKvDtrIquA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-06T22:00:07Z"
    mac: ENC[AES256_GCM,data:of2xNF0Y7Lw6oeLbSv0d4rjpU2v68SNvQz2u/vg7mNUo6oIqjMkhDHWAGEq3h1dqGH/qv6eaX0RBJ0eMmThSSkxbvVMYSdHbGVIYyf+phPEzSZAA2OUvM0dkovhiEcQAsL2GkkASZlIeu19obCON4IqLBcYZCUEDKrCnJTMGU0k=,iv:YByqSFIkam2yPYLvhv1tIUHl7Ae8Ch5ytuciFs0pO/o=,tag:9jD1jy6dAlsQcHOd/UqZLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
