apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:zq1InCnF1D4UaQ9S2xkE1+6XiI8eb+L/RVqYCg6LaXncm0vMmPyn3A==,iv:8N4FbmD/C9BLRKCWvFL5spfGZa1EbitCa11tw9C4x5U=,tag:wrvKSZvsOiw8U6hGLaBD0g==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:v83m82OCOEjD0LLaMuaA5Ow7G5dE2QJGiJOzvzZmEw1DL7jrQ+zKeXeytbpgWcMP1Op7jRv74YwjH8hvC5B1uKtORiVDmLVuWb9vX5cEP3q34HiXgYK5e3/KA3/IhvGvzjwYciffCC4Uhi+V+IJ5dpEgIwLC4zbNtKsrAI3LeRQ=,iv:lScOipsOkpT3ceSNh9ERzQGtTqSMkX16BvW1hPriV6Q=,tag:WfdcLQaXiSsqPibOKLPO/Q==,type:str]
    SSO_DOMAIN_PREFIX: ENC[AES256_GCM,data:w8A=,iv:dSdhKIP62kiQ+PHrvJjIksJqgT60HgfNMSW5A/K1U/8=,tag:LccvulZww+QMtfvjmLnRZA==,type:str]
sops:
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN0h6S01SejdXcENkTWNU
            SExDZms0T3lpTExUbE9RUUJ4RmU5NTdpaDBBCkFmTlc0SWl6QWQxMEM0NCtGblJy
            Q3A5dU85d0FkUGZ6RWFqM24rZ2d1UGMKLS0tIEl2bjRTK1dwb0pUL045Z0kxRXJR
            aVhQYmJzNkU4QmQ1bUVwOVJzS2pHUUkKm+PZsZTLovGY6BLuwhry+zb7/VtVBQPx
            r09Owke7YAL698MUpEdTGDAFI6XHluz5nd9dtXULLUvxL8JkfEWLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T21:30:09Z"
    mac: ENC[AES256_GCM,data:VwvNtXoq24Kd3dW3ro3w9uRFcWAzzTpu3UowaNoRSj0YJXeLMpjX0fktFNqiL7Lwlvu9tqPHP+WKHElXtdFULA1ftFlxEcWhNZJloWyU2bVkFN3O41Mj793PFlf5yOdWuHtTVR7e9bAGrCf3q0AsVIMUXEeJxl1Y7/wpfg60f1c=,iv:pjLqvF33Lr64KcwgIsmTMbRzyJLZrJwZQBWXLNml9gg=,tag:1surWbUPnwik6v/S41chGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
