---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./frigate/ks.yaml
  - ./mosquitto/ks.yaml
  - ./home-assistant/ks.yaml
  # - ./scrypted/ks.yaml
  - ./matter-server/ks.yaml
  - ./music-assistant/ks.yaml
  - ./govee2mqtt/ks.yaml
  - ./wyoming-piper/ks.yaml
  - ./wyoming-whisper/ks.yaml
  - ./wyoming-gigaam-ctc/ks.yaml
  - ./silerotts/ks.yaml