---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homechart
spec:
  interval: 15m
  chart:
    spec:
      chart: homechart
      version: 1.0.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: homechart
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    homechart:
    # Configure Homechart specific settings here
    config:
      # Specify environment variables below, either as plain text values or secrets
      secrets: {}
      values:
        HOMECHART_APP_BASEURL: "https://home.${SECRET_DOMAIN}"
    # Configure Homechart deployment settings here
    deployment:
      affinity: {}
      annotations: {}
      imagePullSecrets: []
      nodeSelector: {}
      repository: ghcr.io/candiddev/homechart:latest
      resources: {}
      # You can run multiple instances of Homechart for high availability, it defaults to one.
      replicas: 1
      tolerations: {}
    # Configure Homechart ingress settings here
    ingress:
      annotations: {}
      # Change this to the hostname you want to use for Homechart.  Make sure you set HOMECHART_APP_BASEURL to include this under homechart.config.values, e.g. if host is example.com, and you're using TLS, HOMECHART_APP_BASEURL should be https://example.com
      host: "home.${SECRET_DOMAIN}"
      ingressClassName: "internal"
      # Configure TLS settings for the ingress.
      tls:
        - hosts:
          - "home.${SECRET_DOMAIN}"

    postgresql:
      config:
        password: ${HOMECHART_PG_PASSWORD}
        username: ${HOMECHART_PG_USER}
      # Disable PostgreSQL StatefulSet if you're using a shared PostgreSQL instance.
      enabled: true
      statefulset:
        affinity: {}
        annotations: {}
        imagePullPolicy: Always
        imagePullSecrets: []
        nodeSelector: {}
        repository: docker.io/library/postgres:14
        storageAccessModes:
          - ReadWriteOnce
        # Change this if you want the PostgreSQL StatefulSet to use a specific disk type.
        storageClassName: "longhorn-fast"
        storageSize: 2Gi
        uid: 100