###################################################################################################
# Recyclarr Configuration Template: SQP-2                                                         #
# Updated: 2024-10-02                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
radarr:
  sqp-2:
    base_url: http://radarr.media.svc.cluster.local:8049
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-sqp-uhd
      - template: radarr-quality-profile-sqp-2
      - template: radarr-custom-formats-sqp-2

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Movie Versions
      # Uncomment any of the following lines to prefer these movie versions
      - trash_ids:
          # - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          # - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          # - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          # - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: SQP-2

      # Misc
      - trash_ids:
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
        assign_scores_to:
          - name: SQP-2
            score: 0 # Uncomment this line to enable x264 releases

      # Unwanted
      - trash_ids:
          # Uncomment the next six lines to block all x265 HD releases
          # - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        # assign_scores_to:
          # - name: SQP-2
            # score: 0
      # - trash_ids:
          # - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: SQP-2

      # Optional
      - trash_ids:
          # Uncomment the next two lines if you have a setup that supports HDR10+
          # - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          # - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost

          # Comment out the next line if you and all of your users' setups are fully DV compatible
          # - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)

          # Uncomment any of the following if you want them to be added to the quality profile
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
          # - f700d29429c023a5734505e77daeaea7 # DV (Disk)
        assign_scores_to:
          - name: SQP-2

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 9c38ebb7384dada637be8899efa68e6f # SDR
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-2

sonarr:
  sonarr:
    base_url: http://sonarr.media.svc.cluster.local:8049
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_definition:
      type: series

    quality_profiles:
      - name: Tuned-UHD
        min_format_score: 0
        qualities:
          - name: Blueray-2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: HDTV-2160p
          - name: Bluray-2160p
          - name: Bluray-2160p Remux
          - name: Bluray-1080p
          - name: Bluray-1080p Remux
          - name: WEB 1080p
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBRip-720p
              - WEBDL-720p
          - name: HDTV-1080p
          - name: HDTV-720p
        quality_sort: top
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 999999999

    custom_formats:
      # Audio Advanced #1
      - trash_ids:
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD ATMOS
          - 9d00418ba386a083fbf4d58235fc37ef # DTS X
          - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
          - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
          - c429417a57ea8c41d57e6990a8b0033f # DTS-HD MA
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - c1a25cd67b5d2e08287c957b1eb903ec # DTS-ES
          - 5964f2a8b3be407d083498e4459d05d0 # DTS
        assign_scores_to:
          - name: Tuned-UHD

      # Audio Advanced #2
      - trash_ids:
          - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
          - 30f70576671ca933adbdcfc736a69718 # PCM
          - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
          - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
          - dbe00161b08a25ac6154c55f95e6318d # DD
        assign_scores_to:
          - name: Tuned-UHD

      # HDR Formats
      - trash_ids:
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - 6d0d8de7b57e35518ac0308b0ddf404e # DV
          - 1f733af03141f068a540eec352589a89 # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd # DV SDR
          - a3d82cbef5039f8d295478d28a887159 # HDR10+
          - 3497799d29a085e2ac2df9d468413c94 # HDR10
          - 3e2c4e748b64a1a1118e0ea3f4cf6875 # HDR
          - bb019e1cd00f304f80971c965de064dc # HDR (undefined)
          - 2a7e3be05d3861d6df7171ec74cad727 # PQ
          - 17e889ce13117940092308f48b48b45b # HLG
        assign_scores_to:
          - name: Tuned-UHD

      # Series Versions
      - trash_ids:
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
        assign_scores_to:
          - name: Tuned-UHD

      # Unwanted
      - trash_ids:
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
        assign_scores_to:
          - name: Tuned-UHD

      # HQ Source Groups
      - trash_ids:
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
        assign_scores_to:
          - name: Tuned-UHD

      # Streaming Services
      - trash_ids:
          - d660701077794679fd59e8bdf4ce3a29  # AMZN
          - f67c9ca88f463a48346062e8ad07713f  # ATVP
          - 4e9a630db98d5391aec1368a0256e2fe  # CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb  # DCU
          - 89358767a60cc28783cdc3d0be9388a4  # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6  # HBO
          - a880d6abc21e7c16884f3ae393f84179  # HMAX
          - f6cce30f1733d5c8194222a7507909bb  # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c  # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c  # MAX
          - d34870697c9db575f17700212167be23  # NF
          - b2b980877494b560443631eb1f473867  # NLZ
          - fb1a91cdc0f26f7ca0696e0e95274645  # OViD
          - 1656adc6d7bb2c8cca6acfb6592db421  # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195  # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467  # QIBI
          - c30d2958827d1867c73318a5a2957eb1  # RED
          - ae58039e1319178e6be73caab5c42166  # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213  # STAN
          - 5d2317d99af813b6529c7ebf01c83533  # VDL
          - 77a7b25585c18af08f60b1547bb9b4fb  # CC
        assign_scores_to:
          - name: Tuned-UHD

      # Misc
      - trash_ids:
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
        assign_scores_to:
          - name: Tuned-UHD

      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: Tuned-UHD
            score: 0