# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:1IHRwHyWO828Few=,iv:zWsDmXYKQyTCb2A6F+hdkYli0fFg6v8TfZNNGFuNg/o=,tag:IhDR4Fv/SFfNTbzy9ydNbA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AP0t/sr6iNzVDtrKGf+Fy4M13mNip0S9ENrRuPIrTLv0yUBW,iv:9cc4o9JH8B79VUxesgtnniLUW9dFVTSAlv0qFK8FPRE=,tag:YraYPvuZwNBct9hSLj5dww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RW5rQmRnbW5zd2NVd25D
        czVDZEdPTWo5NFJEVHlIbzAzMk9JSHY2NlZrCnNBS0dtK2pyRys1b2ZkS0FiSmwz
        eU1EZUNveDVCWjlaOWx2aFhBQmRsZ1EKLS0tIENERElsamRaN1JBVHFxM25iSHVE
        d1pDdXNyUm9VWlRRUXhRT3dtd05yRzAKFsC58KL8iF8kcK1bzMG4ArytP67lKpDd
        CWy33Dbc9O+tR8tdo2JlMiuRZ4ZrePIag5YqgnG586WrNE8MZLvcLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:58:49Z"
  mac: ENC[AES256_GCM,data:hUZ1RnSAv3zsTU7ruI3RNTlsGyJTCYxQDMCMm0Psj2GKhL32u+ln2QeMF14Wx4RqxO0ZaBRvDLcMufV/BUkIW/b0/nG3i2A/Zp44rJJkwFhNe8DGf/nYMbH3jBRhlDZS9NVhnjLdKDB/qmev13ldS6YOXVa4fg4nmCwcaxubY7I=,iv:xSlOtcbyksjQX7fLueF/S4hPp+ZyG7pblaPPXJg1rpE=,tag:ZeIKzDkVKNCUF0Yz/nor6w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
