# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:El//xIbYf+zE1UI=,iv:cCq5i8SJA2m1Fqoy76PbPMDWnz2qgW5MFY9DqNeWUHM=,tag:Mg2CeWACZvI/HMy8zL596Q==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:kWUBI11GkoIXKPVnjhAlRfdPcFVt+4xv+tPJk4lPt0CickWf,iv:jZvPRZT9Ti7/+WYvAohLpdeJEtkO8bpNSgzJj7UE/Jw=,tag:aIV1caG+iBE292+GSjQh5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybzVhZ21KWlg4QXNQbTNj
        QTlBMXVBWTBxb1F3b0FMc1pwVU9SQUZwK0hVCnN6UW1UcUpaWHR1MGZiR01reGJH
        bXZiUU5lRGFITjNvZExQUGZHY0lqTlEKLS0tIC9Dd2grbk51WHI4TTNKUGNvOGhj
        T0VjVWxpQUxEU1N4THFvaHBZdmg4eGcKClnbKSOw0jaRKj2oGAUF29zqeghd15oe
        AMb7XAV+dsLI4scpNEBvN+8vJgn4RVZa+P7hcdi0pSV9c8AjIRnjyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:20:08Z"
  mac: ENC[AES256_GCM,data:pP50cuyz5nRwXOJhr1VDv/i1mZdn5U6NQRDnDNUprVKheMf9k+inLgtDZlzARrRjp9eSaAbt3F/yH5cxsxqqEwCEV1rdwEAuF3TwD2HYgTQPvxsRYK8tk5N0jx61cgyLMomMazHbykDk15B1pQE7J+548QZrZcq4LQUHjFuSouo=,iv:2VA+0kAapd8u9OKG52gq0GjGpJGc5o+3r7i1sdAColU=,tag:s7gitL1HUbNK40yuxnpmbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
