---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: main
  namespace: database
spec:
  replicas: 1
  secretName: mysql-main
  backupSecretName: mysql-main-backup
  backupSchedule: "@daily"
  backupURL: s3://mysql-main
  backupRemoteDeletePolicy: retain
  backupScheduleJobsHistoryLimit: 10
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
       - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-fast