---
apiVersion: v1
kind: Service
metadata:
  name: mysql-main
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mysql.${SECRET_DOMAIN}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    mysql.presslabs.org/cluster: main