---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: comfyui
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ai
  path: ./kubernetes/apps/ai/comfyui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false