---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flamingo
spec:
  interval: 10m
  targetNamespace: argocd
  chart:
    spec:
      chart: argo-cd
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: argo-helm-repo
        namespace: flux-system
  values:
    global:
      domain: &host flamingo.${SECRET_DOMAIN}
      image:
        repository: ghcr.io/flux-subsystem-argo/fsa/argocd
        tag: v2.10.5-fl.23-main-5958964b
    configs:
      cm:
        application.instanceLabelKey: argocd.argoproj.io/instance
        exec.enabled: true
        timeout.reconciliation: 15s
      params:
        server.insecure: true
    secret:
      argocdServerAdminPassword: ${ARGOCD_ADMIN_PASSWORD}
    redis:
      enabled: false
    externalRedis:
      host: "redis-sentinel.database.svc.cluster.local"
      port: 6379
    server:
      ingress:
        enabled: true
        ingressClassName: "internal"
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        hostname: *host
        path: /
        pathType: Prefix
        extraTls:
          - hosts:
            - *host
            secretName: flamingo-tls