# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:95QszNLHEcNdhWy8+KnTyQwBGvqJq3GfZYv+caD3ylzWD0HiJz6J+Q==,iv:MH5I7zdkOdpXfsMN4O1x/cLgoKMmVJImdr5abowNe9k=,tag:yKD+KlcHaw8WKWPIsxuysA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVXV3QUtzSDkrWEhiM2tQ
        aFo4Tks3SVlLeG5rK2I2TVd3TUNyeDhtanlrCmlnVU1yc2Uxd0tpTWtPMXVXV1N0
        dXN4d1pRd3VaL2hRYndBZG05RjBobUUKLS0tIE9MNkVNMHgxU1MzZUFLNUFEZmI5
        QnkxcjkraWZnbG95MVZJVm9EVjNXWHMKH105XRf1++pUhuiQpQSst+DzLwTnfJcI
        HJu3Wu3bKPxmF//4O6TgnDP4ZBOFd1/RHQLpWrXGy0cP9ZSYHJkoRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T21:10:10Z"
  mac: ENC[AES256_GCM,data:ssTpWWfVhufJ+sIfpAWCRBR/RpsvDC6J96wjUEz2gqP9yCiYFsRVJ1RFAy+e0t2RdJR64JzlcmM+tXNu+hTdIASRObcAcWJtlkOKrgobRVYBWD8hwOXpzKHBehbhAF2EyKxUpY/kPpaI5c2LJrXqyuZh6Y/cQgZRKlBAoBIDQdY=,iv:by/782Kh4yYWi1DwCYaFI8kwByiK1pymIFpTxgSRul8=,tag:5kFPUKxDCrUT8MtT5zr/Tg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
