# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:QYs8u19eZCsIh0IOEIebdIUFe1176GaqG2gfoa24A5uIYkiuw/6tDw==,iv:JkkWGCz9ghlH2FIJG5437M+cxLSg7zi/ieiD/hmVzbo=,tag:Sbuv0jE9RogpLmMo4GRD9w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RnRidUdSWjhBWWlSNU1H
        OWFYdGN6dTVqMUdlVmpJbUxDN2lrejRtZWhBCkR2MzlzNmgwYjA1ZWZORGluTGdy
        R1UzZVozVHh4Z0F5bWZSZmRxbzNsMDgKLS0tIFZZMHJpL0JBbXRYTG9XbUt1T21Z
        Znp5eE9UZHQxMEJBY25zYnZZUzlMdHMKUJaKsXakYXR/MeNGaZcvLXtIHAdzAXqw
        TFJqAvi9RdnzU1ax2rYoP8+vVYlV0aWLsSH/Pch77e9+iGEaz/wJYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:20:08Z"
  mac: ENC[AES256_GCM,data:VS8mt6Q0fvJq/jdnf/R6qve2GXFeJCESn3uoHeefiDXdXa9eM7g170bB7CK4zN/FMzMMSlLkGEZMLaCLQ/A7ZbPvlD0Ef45ZLhVV8PgAi9yS2KHSOhJsd7izgcK7FH7hMaBygxn/cQ7xC68qgN4mvjjzQXG3xxnuyKVZG+EHICM=,iv:bl7ir7oAmf1t/gP40JNbl3OyjzxgMsh6EQMhUN/0rMM=,tag:APTkDIUuwU1+RuNBzVNP4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
