# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:PkrlGxEns0CF+pCUX4Zd1bsu6qgN+ZDiRmHKVyPyHGgf8PBzxBOGvw==,iv:5qljb5V6GsoWYPL5+lUJCTa6k/wjudVg6hoBcZxCXlA=,tag:56ybdAIEvoqkeSZuaKSFaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQlcvTVB2bS9haENHMTJm
            QlA1T0lCZVZXQkZnenUxdkpaamtmbXVoUEFRClhpOUJMTGdTcU1CaTVwc0xpZE53
            SkdVd1laUUdmVE5UQWtOSUgrS1dUYUkKLS0tIDdiNGdhRm83YkJ3QTUvZGFSZkx6
            djFWQWZ1bHJaQzd1WExTb0ZDV0lHZkUKv1n/EYIOMYMzEySso9wRQxC0WeBoz6ce
            2HY4MCLZM//71UYUxiMy5DXk8YIQjV20N8hsSaEG7oOdeNnC0MhZ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T23:22:22Z"
    mac: ENC[AES256_GCM,data:B+hX+uA15R8NgEPJBxoCbZ0zXTnOvEO7YCAQzQ6sqHWLsUeQR55K2l+5mJoPqocWjNVdIvT+75689ekAdmjwFynD+N8N/9KywJRBkKgqTOLfthVJiDtL7Z6soBci7+MWwvL/nQVuGf7ThSXcgKvBCqW5NAfycqN94bTkbwgnUDk=,iv:33AHTq0vMUPG0mAD7rSk9Xb+R2TSJUKLh7YqJPO8G0Q=,tag:0hUplTt/qcVeIptwhO/wOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
