# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2VoR3jKEu1mn2W8jMY4+I9mQakkbMTZzR9iGKn7/2xn70jDSL/K+pg==,iv:FYJA9DGCNqCX0GRp4oIFW9x98E1KXtzJrHsMtEBkYro=,tag:GpELOH2vuAMlxJ/S/6B6fA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL0xrSlJHTnA3d2Q1N2lp
        NW13NlBvTWlGeHE0czRRZmxkVkk2ZlgyVVFBClAwMFJmc05NQS8rQjZJS1R0ZnN3
        L3F3eWc4V0pJbjkwNzdSbUphbTJSZVEKLS0tIFBTbnBxYURXYjNqK3EvcW1ST2Jr
        UitEazJFYzBjLzM2bDI1L1Q4UlVlR2MKooxJ5+H5sAlv+bDaUvgRZQPelLaYArgw
        fgFcuqKdz85Ah18q1VG1IUAvsL6eXIx/oLoKcb98mOeuS3KiorLEiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T22:58:49Z"
  mac: ENC[AES256_GCM,data:05Xg1MPY0p42l0B0DGRjYBcHDWJ2+ZezuDrR/6mRUD5rzgKgbSlTQAh/25NPKofshmSwSBqG6r35Qwgw/TZXGR+Y9ILlf8rNzhQfxUAtLftOp7IDShmlvIRnfBuz/AehhCzGzBUVdicqMlwYonSyB51MwDG87IT/NuIS9OGehmk=,iv:g36Yuz3joQISM7DLboWauOMqb+/OUYJG8c7po13ZtjU=,tag:9sEilkp94QPpVu1fiLkiSw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
