---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app matter-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      hostNetwork: true
    controllers:
      matter-server:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 7.0.1
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              MATTER_SERVER__INSTANCE_NAME: Matter-Server
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host matter.${SECRET_DOMAIN}
              MATTER_SERVER__LOG_LEVEL: info
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 15m
                memory: 184M
              limits:
                memory: 184M
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - NET_BROADCAST
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.108.33"
        ports:
          api:
            enabled: true
            primary: true
            protocol: TCP
            port: *port
        # externalTrafficPolicy: Cluster
    persistence:
      config:
        enabled: true
        existingClaim: matter-server
        advancedMounts:
          matter-server:
            app:
              - path: "/data"
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/server-snippets: |
            location / {
              proxysetheader Upgrade $httpupgrade;
              proxyhttpversion 1.1;
              proxysetheader X-Forwarded-Host $httphost;
              proxysetheader X-Forwarded-Proto $scheme;
              proxysetheader X-Forwarded-For $remoteaddr;
              proxysetheader Host $host;
              proxysetheader Connection "upgrade";
              proxycachebypass $httpupgrade;
              }
        className: internal
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: api