---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast
  volumeName: pvc-26dd0741-be4a-4923-8815-f8bf1a26e4f5
