---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: baibot-config
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true