---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: filesystem-trim
  namespace: storage
spec:
  cron: "0 */10 * * *"
  task: "filesystem-trim"
  groups:
  - default
  retain: 1
  concurrency: 2
  labels:
    longhorn.io/fstrim: "true"