---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-logs-single
      # renovate: registryUrl=https://victoriametrics.github.io/helm-charts chart=victoria-logs-single
      version: 0.8.14
      sourceRef:
        kind: HelmRepository
        name: victoriametrics-charts
        namespace: flux-system
  values:
    printNotes: true
    server:
      enabled: true
      name: server
      extraArgs:
        envflag.enable: "true"
        envflag.prefix: VM_
        loggerFormat: json

      persistentVolume:
        enabled: true
        existingClaim: "victoria-logs"

      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - name: logs.${SECRET_DOMAIN}
            path: /
            port: http
        tls:
          - hosts:
              - logs.${SECRET_DOMAIN}

      service:
        enabled: true
        externalIPs: []
        loadBalancerIP: ""
        loadBalancerSourceRanges: []
        servicePort: 9428
        type: ClusterIP

      statefulSet:
        enabled: true
        podManagementPolicy: OrderedReady
        service:
          enabled: true
          # -- Headless service annotations
          annotations: {}
          # -- Headless service labels
          labels: {}
          # -- Headless service port
          servicePort: 9428
          # Ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

    fluent-bit:
      enabled: true

      daemonSetVolumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/rancher/k3s/agent/containerd
        - name: vl-outputs
          configMap:
            name: vl-outputs

      daemonSetVolumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/rancher/k3s/agent/containerd
          readOnly: true
        - name: vl-outputs
          mountPath: /fluent-bit/etc/conf/vl

      resources: {}

      config:
        # -- Note that Host must be replaced to match your VictoriaLogs service name
        # Default format is: {{release_name}}-victoria-logs-single-server
        outputs: |
          @INCLUDE /fluent-bit/etc/conf/vl/output_*.conf

          [OUTPUT]
              Name http
              Match kube.*
              Host server-server
              port 9428
              compress gzip
              uri /insert/jsonline?_stream_fields=stream,kubernetes_pod_name&_msg_field=log&_time_field=date
              format json_lines
              json_date_format iso8601
              header AccountID 0
              header ProjectID 0
        filters: |
          [FILTER]
              Name kubernetes
              Match kube.*
              Merge_Log On
              Keep_Log On
              K8S-Logging.Parser On
              K8S-Logging.Exclude On
          [FILTER]
              Name                nest
              Match               *
              Wildcard            pod_name
              Operation lift
              Nested_under kubernetes
              Add_prefix   kubernetes_