apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
type: Opaque
stringData:
  ALERTMANAGER_API_TOKEN: ENC[AES256_GCM,data:ciYw12NPl6howv5kSsyMrmxNgrKFp7ZN1w==,iv:9GIfbUpOhUwlDbU69Vs3kaopi3LgKuAesLh0Lp3d+e0=,tag:ffjDeWLlWpaLCVW8r71Dfw==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:kvnK7enY96//4EdJhDbtCixRs6s=,iv:lcCYKmOiLGLMBCCTFfqGurUCWUG/RCi7HJyqMdSqImg=,tag:xvTLyBg9Rcx4AIIuU0ZyEQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFE1UktJaFh4NGl2QTFL
        RlNYdzdsN0JyL2Z5RXVmOGg5R0RZQngzRVRBCnkzNnFaUjlzQTlWVFMwOHFGM1NR
        ZUxOVC96bTJ0V2hPbVdqOTIwRGhtQWMKLS0tIFJXVVNyMEpDbDA3NGNGZEdDSXNw
        VTJndkwvSTVJWkFLbk1UbDFHcm1lTGMK3W4wJYWI9oiDcoKbDHwAyxD1SZNAJ4GM
        tFAebCFUDuxUEGu5sqeHMH7NJKwJKhV4xa4jJdXVCVg1PdfzjkDZkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T21:41:37Z"
  mac: ENC[AES256_GCM,data:SX4UY/mw0gn7MPwTpoe58xbaddnKiZjADT9DuUdsIlA8EqkcN07Pd6xYFF+jx9HELjNaDRD6mkp46a0HqzZvshxPRXpHRKqCS61mofA7foGW1EXnkqL6YeTMzwdOkhNGP7qXNvLYRLPqkaMnWpkyeuWecnY8M6wFZCBoVR6Mcsw=,iv:iJln2Qh5H/bHflCaLsHx0HqFGNQ2kqwASGOqDBMY4Qc=,tag:f8mm308XL3W/gICvK3GS/A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
