---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice-scandata
  labels:
    app.kubernetes.io/name: harbor-jobservice-scandata
    app.kubernetes.io/instance: harbor
spec:
  storageClassName: longhorn-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi