---
# As declared by lord onedr0p:
# Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
web:
  port: $${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: postgres://$${INIT_POSTGRES_USER}:$${INIT_POSTGRES_PASS}@$${INIT_POSTGRES_HOST}:5432/$${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/1236528?s=400&v=4
  link: https://github.com/gelato
  buttons:
    - name: Github
      link: https://github.com/gelato
    - name: Home Cluster
      link: https://github.com/gelato/homecluster
alerting:
  pushover:
    application-token: $${CUSTOM_PUSHOVER_TOKEN}
    user-key: $${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: healthcheck failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 5
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover