---
crds:
  enabled: true
replicaCount: 1
# dns01RecursiveNameservers: 8.8.8.8:53,1.0.0.1:53
dns01RecursiveNameservers: https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
dns01RecursiveNameserversOnly: true
enableCertificateOwnerRef: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
