---
crds:
  enabled: true
replicaCount: 1
dns01RecursiveNameservers: https://dns.quad9.net/dns-query,https://1.1.1.1/dns-query
# dns01RecursiveNameservers: https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
dns01RecursiveNameserversOnly: true
enableCertificateOwnerRef: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
