---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rsync
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: hub.docker.com/eeacms/rsync
              tag: 2.6@sha256:07244cc157ee915ee4095734cd6b68b33bbb807fe59c19a9cd78aa3a1fa3d972
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - jellyfin
                topologyKey: "kubernetes.io/hostname"
    persistence:
      media:
        existingClaim: media-storage
        globalMounts:
          - path: /media
      nfs-media:
        type: nfs
        server: tower.local
        path: /mnt/user/media
        globalMounts:
          - path: /nfs-media
            readOnly: false
