---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: linuxserver/grocy
              tag:  4.5.0
            env:
              - name: TZ
                value: ${TIMEZONE}
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "Grocy - продукты и все такое"
          hajimari.io/enable: "true"
          hajimari.io/instance: "admin"
          hajimari.io/group: "Home"
        hosts:
          - host: &host "grocy.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: grocy-config
        globalMounts:
          - path: /config