apiVersion: v1
kind: Secret
metadata:
    name: harbor-init-secret
stringData:
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5WLAJlPmsI6z5Gfk76BDZA9Nv1soWg==,iv:XQ0sjLUd2OOEq7qE739wBvGrbT65xppPiqUpMXRH1u4=,tag:Ue6bmeVo5uQt6JOA9/pMug==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bAWAfU7VKj/X85p3MEeZfVc=,iv:dFPmUZdSNzhLhKmQN4Depzpp9FDBvbzGzLGmGRDHfOU=,tag:C9jcq2AVPF42JOHXrllwAA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FAnoeqTQ064eaPvO41P6tdtMqOpe,iv:175wMQ789cQTtHN8/niyLIMY25LpBPFuLH5rQIt7xAY=,tag:PV2lHlU2x8Qol7uWu3HvjQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:dRN+5hdR,iv:cBk04tBKYfCDojJJG3c6euCXCCqHO70EiFogW1dbPUM=,tag:hskd5r7CFNE18tJoHBCsag==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:a+UgGplnRkhylLr6W+C3bsjwga3ZwR1lWDV218o8aMBX5pL7ZQrJ+w==,iv:nOkjkecKlHkCNgltJ0OHX2aX7GhQu/M5MjfW2xAhfd4=,tag:47ryxHScr6wiZ0k80+PubQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZHk2RTB0dFJ5c3ZvTGV1
            NkxlS1lzUW1QVzEweWJHWG5UQVBTSTR4eXhBCmFIVzFUaE8vY2RRd3ZNa1RMaVRJ
            andHeWxpLzhRTXlMdThXMzhYbm5SUVEKLS0tIEdybVFMMkJ6ZDZFdWdrODFOUmcw
            V1hUVVpkTGdJcXM0dTdYOVhCVDU3aWsKtrbBpcnhsZlWXTxh8WrhluEp7Rz27z/f
            P4m3W3om0TQYgpKxE0Ob0xh+vPl4iLUxTjSyI6KLquUZ8SWkFRA3MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T21:17:21Z"
    mac: ENC[AES256_GCM,data:xM5AqWojtM/t4z+iw1zFLKp0hvflq8fwVmLK1pC00XBmLM0ytWSdHQ2u7vFMcNips4rIlcdMNABct6tg/K45vM0ZkZaCtpBo1Y8qP0ezNC1F03stDZmTrVvsMp7SwPsxuR7CNj99N2QQnPK1XIBfF/QeLNuhcQ1nLv01/XhIdFc=,iv:l3KF98du3VNNwbvR+zFNBTd7iZ4fNpmbeQHqiiMyeB0=,tag:tFwSAkQLrYyME+GRctFQ/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
