---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stunner-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: stunner-gateway-operator
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: stunner
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    stunnerGatewayOperator:
      enabled: true
      deployment:
        name: stunner-gateway-operator
        securityContext:
          runAsNonRoot: true
        container:
          manager:
            image:
              name: docker.io/l7mp/stunner-gateway-operator
              pullPolicy: IfNotPresent
              tag: 1.0.0
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 25m
                memory: 128Mi
            args:
              - --health-probe-bind-address=:8081
              - --metrics-bind-address=127.0.0.1:8080
              - --leader-elect
              - --zap-log-level=info
            securityContext:
              allowPrivilegeEscalation: false
      dataplane:
        # Can be 'legacy' or 'managed'
        # default is managed
        mode: managed
        spec:
          replicas: 1
          # for dev version set it to docker.io/l7mp/stunnerd:dev
          image:
            name: docker.io/l7mp/stunnerd
            pullPolicy: IfNotPresent
            tag: 1.0.0
          command:
            - stunnerd
          args:
            - -w
            - --udp-thread-num=16
          env: []
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationGracePeriodSeconds: 3600
          enableMetricsEndpoint: false
          hostNetwork: false

    stunnerAuthService:
      enabled: true
      deployment:
        replicas: 1
        container:
          authService:
            securityContext:
              runAsNonRoot: true
            image:
              name: docker.io/l7mp/stunner-auth-server
              pullPolicy: IfNotPresent
              tag: 1.0.0
            resources:
              limits:
                cpu: 200m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 64Mi
            args:
              - --port=8088
              - -v