---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  # - ./config/gateway.yaml
  # - ./config/gatewayclass.yaml
  # - ./config/gatewayconfig.yaml
  # - ./config/udproute.yaml