---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-local-hostpath
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        name: democratic-csi-charts
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csiDriver:
      name: local-hostpath.democratic-csi.k8s.home.arpa
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File

    storageClasses:
      - name: local-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true

    volumeSnapshotClasses:
      - name: hostpath-snapshot
        deletionPolicy: Delete
        parameters:
          cluster: k8s

    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
      nodeSelector: &nodeSelector
        node-role.kubernetes.io/worker: "true"

    driver:
      config:
        driver: local-hostpath
        instance_id: tau
        local-hostpath:
          shareBasePath: &local-hostpath /var/lib/csi-local-hostpath
          controllerBasePath: *local-hostpath
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0

    node:
      mount:
        checkFilesystem:
          ext4:
            enabled: true
      driver:
        extraVolumeMounts:
          - name: local-storage
            mountPath: *local-hostpath
            mountPropagation: Bidirectional

      extraVolumes:
        - name: local-storage
          hostPath:
            path: /mnt/buffer/local-hostpath
            type: DirectoryOrCreate
      nodeSelector: *nodeSelector