apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Eh1+zImzbWmlcSVmWlgoJvRiIJ+VEA==,iv:a6OEyGvk7TTCF1UetS82E4KlxmNhO1ORHbbNkhg8lSo=,tag:SdMfhJUER93coVP+Vx/Ieg==,type:str]
  password: ENC[AES256_GCM,data:+LXGZUWGkyjJCfD/yTwBZ/xQgKXEgg==,iv:nifg8JMhsDYTOuncS6HqL/0Nn2wEf0KgH3lsD9Mn2nA=,tag:Ie8mjl44IsjjDjVAJsK1pA==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:TW2dweeEZixJcQA20o39tjyK,iv:B9J/SQpApklQh8umv3xBfHtWSpgTTVXQB1YnIGY6AoU=,tag:b9S7Y6nCKF+X1AfiIlIGzA==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:JShp+e0B6LSM9gjDYFnNq3JdBlCgGQ==,iv:Nb6Mey8cECwBKMXVQ6nBxJp/r2EXWgq3bZC5R4HjZvs=,tag:cAy62Anye8bRZnnH3Vfkcw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTitmbFBKbHZJUEJMYUpi
        UGhmZTlBM0x2Y1hFSkYzVThRZzdqQWpRWEdjCmNweklLS2tnclRaYlM1SUJhNktz
        TU1kZzRhTkpNcFVUMGJLc0ZlN0dXOEUKLS0tIG9QTHRVK3RWM0FWaGNxQUc1cElM
        MnpJbjRROVhEQU9XT0JKbDEyb3pPUmcK5WextfrP5Hc2AwD/RijtuGb3aGisg68A
        YJ1umy0S+swHNaImZQ4pCa+rAsAMOgjEbaTt/z5niN41ftn2Z0SCAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-05T22:12:51Z"
  mac: ENC[AES256_GCM,data:2WhejEL73eIt4JwOhYcn2dq+xYylonIBkejP6nZCb3Lpp/Uci9c3Mj1iEr7l5XeBMIpxWR9cigDkObU/WA/D7Se7Q8mZNgiooXjq3n+N70Wh3yKbjY8nAZKrETsl1CwPuY6ftaRRE2SmVQeOxCoGDVc5kW7BhhP7aZu44/VLz4k=,iv:iZYYCT1jK9T7LrFseT6fkXNLyYlRVLoeklBGnuKp77Q=,tag:rtbkDyF7tebwRgfRiNCTcw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
