apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: storage
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1p7F+JM4THEh,iv:Q2FpmOf0nH0TAXrMMBzqVIuPjNsbtB7yUj1tG/khYyM=,tag:j26IehZBSeRkN1p0AVKU/g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cfEgAnrDCozQig==,iv:6ERii8qaDbXBeNrjKJeiJ4cw9K1U6ZsI4NxbMB+hohk=,tag:OkP5nPYtKItLQaxpdr6gkg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:xkU4CIAV9eP2qLmDPRc=,iv:NuSTZMS/81HmSHsMg8Kg2BOlMDggqr/HT3CTwn/HwBc=,tag:9XQoMO/nlKCjE4+wbpXbUA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWTE3dUFSZ1NaNTd6NTZ4
        Zy9ubVlaS1REYWl0a1JEMUthV0hNMnBHUzM4ClQzQzdmSjl0MlBXQVl5cHF5d1RW
        THlCUzU4WURWNndnU0U5WHN4U3NiOXMKLS0tIHpGTktLK2xIR0Y2b0lpdExoYUlO
        Y0MwRnhCcFBsL0RYdWZFNWR4d3IwQWMKH9+SZ4X3ZwB89eK61UjoTAdofubVnY9Q
        GHUkq5usQ1Oq/ovSkuwvuS+UUmiq9ua6C2Vs+ADedj+6mgZjw+bKWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-04T08:51:59Z"
  mac: ENC[AES256_GCM,data:5+HrDSbAPmE3YjzaiKJI1YexibuJilVL2+kaQ5udjoKPygP/qGGX4sfA+exs6IEdFBTwBkl30yzaIL732Z94XViYi4XrB5yv5NQqVqbJthD07vockUGXUkV7MT9reM0mLcoqmE0gdLZ44GuX8pWHf8VKLr5NN6nLbII6CnE3yw0=,iv:epCqZSWz2n3fjic69p3hZ4ACHC2jJN3d5bThv5baYP4=,tag:wy1q6UBMOiBZJiaxYQ3pyA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
