apiVersion: v1
kind: Secret
metadata:
    name: ghost-secret
stringData:
    database__connection__host: ENC[AES256_GCM,data:BUpudUq7+C2Lqma8Og7k02BIii86l7c=,iv:mI6PJ2/3J7BMlIbHPsBKrlz3GZm4Dzgx/Aav9QXHeQE=,tag:3ERMAVeIzrDy+BrjRMUudQ==,type:str]
    database__connection__user: ENC[AES256_GCM,data:AXV5fMvwqv+BJA==,iv:qvWfmppWD/4l3Q9UaRuVIjGmH37r3c3oIupe2/IedR4=,tag:vuI8kUkHllNTbDmKmbM34g==,type:str]
    database__connection__database: ENC[AES256_GCM,data:UTD/n9298t4=,iv:MQX/uwJUIsm7Utxabkin+Kg4nWwZKHdOAH+l0tFifXI=,tag:uAz3qjWWzfd5MRZCg4nalA==,type:str]
    database__connection__password: ENC[AES256_GCM,data:vbp0ovPkfpaWXFZP+qHZ0/QIAsY=,iv:6JYOGouFurMp/rluQb93FSv4DXFwVBHRQEbjeerryCw=,tag:sG0PWzOwFPGQmexD00x2Gg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:9tAfUbR73Q+aq7crGw2j2xPZHLDOzW3vH2pQ,iv:wZ4FbrRA95mI8mBogzBpjb+lsfEONg6zS5RljsJ1ql0=,tag:enttUqOaq9S1dHsO0ALdhQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:kwqSpCCLs9JPB7Z3Sunr2VO019U=,iv:phZIRfQDS7vFmx9tOkMkdrNbQYMYNPAv6/rArezohCQ=,tag:ONXsXj6Pwa6cBFBHPB3ydw==,type:str]
sops:
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMTdkclNYVUEwNzhRUlpa
            L3BVOTZwcTVsKzN3d2lqeStIN1FqSjdHSTFVCk5VOTJ2eXRMQ05SdzMxM3diVHM3
            Unp0T1JxVmpJSEhRdXZkRS9xZ29KcXMKLS0tIDB3ZnFpakZnYVo1VDhIa0NPOURB
            SERZRTRIcUNDLzdESDlWajVaSXphUGsK5DTUH+2EpoOj4vWA5qq7tSltXAimNc5u
            jTZn+4Q0qhdsyIdcwEoUAHMRKI81EVuwajHVqM+LkZPHixcsXtY24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T12:21:04Z"
    mac: ENC[AES256_GCM,data:eIMB2nGP9qax2GzXj7nNZCgKT5tdm6Ygpy/QKxsZSp5McG8eVXVYwFf05IYcYHIXG10Sc3a9CPtE4rt7F3ICCHu1rHm5OAhs7AcweH8+IhZy7mkD6CgZXUCD8ABWo47xdF5PxLUMTDHAUi1mpW54kzX2p9yguMtrvTuxpLInrZk=,iv:vcSjp7Iz7sn6llePqDyTN+rG4UnUT+vomRqJMDlgXnA=,tag:04m/nTW3cwMud1vU3fUtxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
