apiVersion: v1
kind: Secret
metadata:
    name: ghost-secret
stringData:
    database__connection__host: ENC[AES256_GCM,data:BUpudUq7+C2Lqma8Og7k02BIii86l7c=,iv:mI6PJ2/3J7BMlIbHPsBKrlz3GZm4Dzgx/Aav9QXHeQE=,tag:3ERMAVeIzrDy+BrjRMUudQ==,type:str]
    database__connection__user: ENC[AES256_GCM,data:AXV5fMvwqv+BJA==,iv:qvWfmppWD/4l3Q9UaRuVIjGmH37r3c3oIupe2/IedR4=,tag:vuI8kUkHllNTbDmKmbM34g==,type:str]
    database__connection__database: ENC[AES256_GCM,data:UTD/n9298t4=,iv:MQX/uwJUIsm7Utxabkin+Kg4nWwZKHdOAH+l0tFifXI=,tag:uAz3qjWWzfd5MRZCg4nalA==,type:str]
    database__connection__password: ENC[AES256_GCM,data:vbp0ovPkfpaWXFZP+qHZ0/QIAsY=,iv:6JYOGouFurMp/rluQb93FSv4DXFwVBHRQEbjeerryCw=,tag:sG0PWzOwFPGQmexD00x2Gg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:9tAfUbR73Q+aq7crGw2j2xPZHLDOzW3vH2pQ,iv:wZ4FbrRA95mI8mBogzBpjb+lsfEONg6zS5RljsJ1ql0=,tag:enttUqOaq9S1dHsO0ALdhQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:kwqSpCCLs9JPB7Z3Sunr2VO019U=,iv:phZIRfQDS7vFmx9tOkMkdrNbQYMYNPAv6/rArezohCQ=,tag:ONXsXj6Pwa6cBFBHPB3ydw==,type:str]
    #ENC[AES256_GCM,data:SqRN5pUBq3nh+Q29c+CQp9u0xKo0pBAs9xZ8Ix5QEboCz6BCDrMm5ho=,iv:MnpMiAc8USmcSqicOPTfvTwc4XHswOzXR9XFJcCKBBY=,tag:X8Iedd8Eupqk85y+fqe1LQ==,type:comment]
    #ENC[AES256_GCM,data:vbsA/ZU49jZiTT6nqtYI8VQVllhq8u9LPV+RXhzSGTwIRRo8N2s=,iv:OmMP+71rz7gNPJoz/Qkd8i+5x9rnbWq2g2Ek8/cY2UM=,tag:/LbSISF5SFHSaixsmp1yjg==,type:comment]
    mail__options__host: ENC[AES256_GCM,data:X4mstKLQnoIYtPy0kMZjPlGINLB4IVRN0LMFs4MBHCK0bVVc,iv:sFHxBCnlAjh8kMC137DTUB0Ie8ufulA7S8YXVw6RLMQ=,tag:rUom0SB/VIOhDXpLHMkjvw==,type:str]
    mail__options__port: ENC[AES256_GCM,data:cv0=,iv:/fnMLeboTDXaOcEltuIgsONJnjb4GWesX1Fluj77ebY=,tag:8bvoqgl4+ZGBerMaA5g6Lw==,type:str]
    mail__options__secure: ENC[AES256_GCM,data:WP0aoK8=,iv:B9tml2hoYPu1jOYgFlM2Kkc88eOvl0ShfJ2Z8QuOyCI=,tag:hH8QnoIpiufxws5ViEcRJg==,type:str]
    mail__options__service: ENC[AES256_GCM,data:JbGka+Y=,iv:4WnKMLsQQumtk6Lr/bljx6SSHDorsaXk8k+2cTyQj38=,tag:vHl6KOyR/tDwHZUSiLZlhQ==,type:str]
    mail__transport: ENC[AES256_GCM,data:r48VgA==,iv:IKOQPlPc6VLL/5ADkDsQ7T90JGMQtdEZ5CVfrzVvDeU=,tag:MmTyj+OPSSnziaZZdQNtPw==,type:str]
sops:
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMTdkclNYVUEwNzhRUlpa
            L3BVOTZwcTVsKzN3d2lqeStIN1FqSjdHSTFVCk5VOTJ2eXRMQ05SdzMxM3diVHM3
            Unp0T1JxVmpJSEhRdXZkRS9xZ29KcXMKLS0tIDB3ZnFpakZnYVo1VDhIa0NPOURB
            SERZRTRIcUNDLzdESDlWajVaSXphUGsK5DTUH+2EpoOj4vWA5qq7tSltXAimNc5u
            jTZn+4Q0qhdsyIdcwEoUAHMRKI81EVuwajHVqM+LkZPHixcsXtY24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T10:04:20Z"
    mac: ENC[AES256_GCM,data:s0ZqD5S3ygMfYtO8XwBXTZS3pgL9JutkzIsQ3gLXtAsw+9IBqPLwf3hIolb7bnQGsXhGtCjjYJ3YFeuUHYOUfJQYTnRod8/vW3PIQ5LzF+97vT4tZploK1Ob6sEWvPYbb2ltqdLiGBpQ4mCsVws7rCjNhvXoVLAdVQuezcOoPeQ=,iv:AtEtePDlmQZv2daZv4p53wBKUMOzabMmlieJVqBymFA=,tag:4em6nehkoYqXUt/evkta0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
