---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app democratic-csi-local-hostpath
  namespace: flux-system
spec:
  targetNamespace: storage
  path: ./kubernetes/apps/storage/democratic-csi/local-hostpath
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substitute:
      APP: *app