apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-webui
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
#      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx-internal
      namespace: network
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: flux-webui
    adminUser:
      create: true
      username: admin
      passwordHash: ${WW_ADMIN_PASSWORD}
    ingress:
      className: internal
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:flux
      hosts:
        - host: &host "flux.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    resources:
      requests:
        cpu: 15m
        memory: 202M
      limits:
        memory: 1458M
