apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
    namespace: matrix
stringData:
    POSTGRES_SYNAPSE_USERNAME: ENC[AES256_GCM,data:xGH+bpWmpLHt+JzuNZ8nMeKk/nypWTcdcr0/Y8yHvA4DdbA=,iv:rlZJEECEKEunp/MlLGLurBTg/CSPRDxzXHlZbVnhqoE=,tag:16PTZ6iSqFPR1teCdE2htA==,type:str]
    POSTGRES_SYNAPSE_PASSWORD: ENC[AES256_GCM,data:Z4hbbRmc1jf83HqTGwl/MlBQgGqqzDKEjUo/oyhiExnnM2A=,iv:7kRx/+6J7eSzn8PltZNF0XkNV1eOOqvCm1Y72J/ABoY=,tag:l37yOol6Ma9pk1k2CiS5JQ==,type:str]
    POSTGRES_SYNAPSE_DBNAME: ENC[AES256_GCM,data:vMTn2JDU3NXUF6qEJ22eLSGVjVsJlDjpFhaF8ZSYKcEE,iv:W5dQfu5uTiSzImQwjoZt1Se/GqHmliUl/bizRHCZL/k=,tag:Wh4MzcbGYGh9iQ+llaLjvA==,type:str]
    signing.key: ENC[AES256_GCM,data:DueCW+c1n8n1u0oJiQnbbWcB,iv:JWwMfW8EJ+moK/rn9taz5BqeriaamRgWcl5DZWrflQo=,tag:vtPSXY650hXnwL4oc/DZXA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2yDHeksMgsAnMCaO+QnGjiBXXQipzZxp4Bekle3xt1jB,iv:VqjJ86MFOoEY9plJjxPCSQtCvcwcu95a+WpEaZ6JyU0=,tag:isNKLtR9LVF5g5Hx0cQ89A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4Pre90CWFRiNU8IDCETKzOMsg0B1FMaXGpge7Ux39tMmZFedKUDpJg==,iv:rcm9Y/LdxBGtKmFyqZMjrzxAxFHIE7/BTFpcCXalKo8=,tag:xJJ13+1zSslZARYWgY5jgg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:eJMyxx2mmLp2PdQQz5quzrWl5LmEfkVwyRjBvLPK2c52+Vw=,iv:JsmLggfOvU3tjvragr1jTI5i1Sr0x8VFrW0OJ8PMUBo=,tag:qoyRZMkf0m863RH7d/ZHVQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gMUK1XMKP2ubtMI4jZLG8JRKYMnQmR5WjkIodL5PfI7kyEI=,iv:+kTzrnR1rBv3dRfU47pjeAzKY/uoWMauR23rAIjOj98=,tag:Tntvf4hNZ2KBr/16/9/UGw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:jZmxKMj8/nszHTOXxrvNJN3s8vj9pA==,iv:9H0EXvBKQ0kHSgkxWw98OHn/s8XXRchSpT/bPCUbhs8=,tag:rqXfjaJeh+1WPgYsVv3SYQ==,type:str]
    MATRIX_CLIENT_ID: ENC[AES256_GCM,data:4VbV,iv:slJmDVRy5wlcqidkblavNNQezAvgqkY5wfdBIJncS9g=,tag:ytsoE/6grUcPq8ujE2CnAw==,type:str]
    MATRIX_CLIENT_SECRET: ENC[AES256_GCM,data:oyw9,iv:QYm5T080jq0VoNfWxuZ1POMQS8VVrCo9t2SAtQphRHU=,tag:0smru6P441rBha3pcMKHMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQklKZ3BlREdQWGxlRUNY
            N3F1ZDJRZTMyUmhQeXMyQ2oyREVab2FSc0cwCk1qOGFGZ3NSVlRObk53U1dhT084
            Z2twWXBLUHFRYkg4U05yTCtIVGdyaWcKLS0tIGp0cllFOHA0RExkelJwNjRpUUE5
            S2dpM1RtbUhDQ2tSN1hwMGloQ1c0cjgK5CgKMKTNYZaHF4ln2FXrpR35EO8OnNRA
            CJDPC4TFK+KXaoJVqBokl+w5sVW/plNcB/8qz4WKS1eRYZ+NcZJZ/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T22:50:20Z"
    mac: ENC[AES256_GCM,data:Cn4wWqOtVp1CTFaM+IOjpxWZ5N+EHK5Ybn0c+L3OwFt4+2d6wfD4n6HW27NCtuG/7jutSttiLbbV13GsELUJ3skfp9xFlqBg2PreSDqqyewuQA+zQHIYq/4WxOsK24OKDm3TIK8gqiOzE5km5GTgivKxD0M4Snjk7rNhpZtdGmA=,iv:6utbte6UMwRC0JiAQwwe5sODLVW91gYzH2dWdm9xbLw=,tag:mraS0kNiA3p4TUHJtVik0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
