apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
    namespace: matrix
stringData:
    POSTGRES_SYNAPSE_PASSWORD: ENC[AES256_GCM,data:Z4hbbRmc1jf83HqTGwl/MlBQgGqqzDKEjUo/oyhiExnnM2A=,iv:7kRx/+6J7eSzn8PltZNF0XkNV1eOOqvCm1Y72J/ABoY=,tag:l37yOol6Ma9pk1k2CiS5JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w77q45vfakc48tq3zp35hhdcwxa3zks5vrzwxm9k6ge578zx7gmqkyazy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQklKZ3BlREdQWGxlRUNY
            N3F1ZDJRZTMyUmhQeXMyQ2oyREVab2FSc0cwCk1qOGFGZ3NSVlRObk53U1dhT084
            Z2twWXBLUHFRYkg4U05yTCtIVGdyaWcKLS0tIGp0cllFOHA0RExkelJwNjRpUUE5
            S2dpM1RtbUhDQ2tSN1hwMGloQ1c0cjgK5CgKMKTNYZaHF4ln2FXrpR35EO8OnNRA
            CJDPC4TFK+KXaoJVqBokl+w5sVW/plNcB/8qz4WKS1eRYZ+NcZJZ/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T22:08:22Z"
    mac: ENC[AES256_GCM,data:BssX2TK8DXaKTmjTtKuBGTZDZrOCri15ue0C0O9PvjyEzTnwldcO2xIaR4dz0yylinYMYc3OpVHrY/73+KcxTUKjV533RDUkbIxJ61yhzNCSwMPw90OkBWAoR0z69c5DmwpAIgnZVJkAna/TCRLFKNe0AcrXtg4PGW+bO8cFj7U=,iv:heAaxmYy32qz/DNgnS2BS0ZOQZ5DihTMDM6JLJcJNME=,tag:8TSMhO8VWhYMcL0o4EYCHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
