---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app silerotts
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
    # defaultPodOptions:
    #   affinity:
    #     nodeAffinity:
    #       preferredDuringSchedulingIgnoredDuringExecution:
    #         - weight: 100
    #           preference:
    #             matchExpressions:
    #               - key: "kubernetes.io/hostname"
    #                 operator: In
    #                 values:
    #                   - k8s-worker3
    controllers:
      silero:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: navatusein/silero-tts-service
              tag: 2.0.0
            env:
              NUMBER_OF_THREADS: 6
              LANGUAGE: ru
              SAMPLE_RATE: 48000
              HA_FIX: True
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              limits:
                memory: 6Gi
                nvidia.com/gpu: 1
              requests:
                cpu: 100m
                memory: 500Mi 

        # pod:
        #   securityContext:
        #     runAsUser: 568
        #     runAsGroup: 568
        #     fsGroup: 568
        #     fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: silero
        ports:
          http:
            port: 9898
            protocol: TCP

    # persistence:
    #   data:
    #     enabled: true
    #     existingClaim: *app
    #     globalMounts:
    #       - path: /data