---
# yaml-language-server: $schema=http://kubernetes-schemas.local.lan:8080/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://github.com/NVIDIA/gpu-operator
      chart: gpu-operator
      version: v24.9.2
      sourceRef:
        kind: HelmRepository
        name: nvidia-operator
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    disableOpenAPIValidation: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml
  values:
    nfd:
      enabled: false
    driver:
      enabled: true
    toolkit:
      enabled: false
      version: v1.16.2-ubuntu20.04
      env:
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"
    devicePlugin:
      config:
        create: true
        name: time-slicing-config
        default: any
        data:
          any: |-
            version: v1
            flags:
              migStrategy: none
            sharing:
              timeSlicing:
                renameByDefault: false
                failRequestsGreaterThanOne: false
                resources:
                  - name: nvidia.com/gpu
                    replicas: 6