---
api:
  listen: :80
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 192.168.108.60:8555
    - stun:8555
  ice_servers:
    - urls:
        - stun:stun.cloudflare.com:3478
streams:
  gates_hq:
      - rtsp://admin:12332145@192.168.108.104:554/stream1
      - "ffmpeg:gates_hq#audio=copy#audio=aac#audio=opus"
  gates_lq:
    - rtsp://admin:12332145@192.168.108.104:554/stream2
    - "ffmpeg:gates_lq#audio=copy#audio=aac#audio=opus"
  door_hq:
    - rtsp://admin:12332145@192.168.108.227:554/stream1
    - "ffmpeg:door_hq#audio=copy#audio=aac#audio=opus"
  door_lq:
    - rtsp://admin:12332145@192.168.108.227:554/stream2
    - "ffmpeg:door_lq#audio=copy#audio=aac#audio=opus"
  dvor_gates_hq:
    - rtsp://admin:12332145@192.168.108.210:554/stream1
    - "ffmpeg:dvor_gates_hq#audio=copy#audio=aac#audio=opus"
  dvor_gates_lq:
    - rtsp://admin:12332145@192.168.108.210:554/stream2
    - "ffmpeg:dvor_gates_lq#audio=copy#audio=aac#audio=opus"
  dom2_hq:
    - rtsp://admin:12332145@192.168.108.215:554/stream1
    - "ffmpeg:dom2_hq#audio=copy#audio=aac#audio=opus"
  dom2_lq:
    - rtsp://admin:12332145@192.168.108.215:554/stream2
    - "ffmpeg:dom2_lq#audio=copy#audio=aac#audio=opus"
  middle_hq:
    - rtsp://admin:12332145@192.168.97.27:554/stream1
    - "ffmpeg:middle_hq#audio=copy#audio=aac#audio=opus"
  middle_lq:
    - rtsp://admin:12332145@192.168.97.27:554/stream2
    - "ffmpeg:middle_lq#audio=copy#audio=aac#audio=opus"
  street_hq:
    - rtsp://admin:12332145@192.168.111.65:554/stream1
    - "ffmpeg:street_hq#audio=copy#audio=aac#audio=opus"
  street_lq:
    - rtsp://admin:12332145@192.168.111.65:554/stream2
    - "ffmpeg:street_lq#audio=copy#audio=aac#audio=opus"