---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: squeezelite
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      hostNetwork: true
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - tau
    controllers:
      squeezelite:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: giof71/squeezelite
              tag: r2-stable-alsa
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            env:
              SQUEEZELITE_MODE: ALSA
              PUID: 1000
              PGID: 1000
              SQUEEZELITE_NAME: tau
              SQUEEZELITE_SERVER_PORT: 3483
              SQUEEZELITE_LOG_CATEGORY_ALL: info
              SQUEEZELITE_MAC_ADDRESS: 5d:1f:20:4e:b2:46

            securityContext:
              privileged: true
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - NET_BROADCAST
            resources:
              requests:
                cpu: 15m
                memory: 184M
              limits:
                memory: 512M

    service:
      app:
        controller: squeezelite
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.108.30"
        ports:
          http:
            port: 3483
    
    persistence:
      snd:
        enabled: true
        type: hostPath
        hostPath: /dev/snd
        globalMounts:
        - path: /dev/snd