# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ananace-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://ananace.gitlab.io/charts