---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ai
  name: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn-fast